### ISSUE TITLE
Fix non-thread safe Flush() in RedirectConsoleWriter

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/msbuild#10013]
> [pre-existing] It looks like the goal of this class is to expose a thread-safe `StringWriter` but this method is not thread-safe. Writes that happen between these two statements may be lost or corrupt the `StringBuilder`.

_Originally posted by @ladipro in https://github.com/dotnet/msbuild/pull/9983#discussion_r1563046625_

**Comment by AR-May** [comment]
team triage: @YuliiaKovalova what is your suggested priority for it?

**Comment by YuliiaKovalova** [comment]
cc: @rokonec MSBuild Server-related topic

**Comment by rokonec** [comment]
Purpose of this class was to redirect all console writes from msbuild server to its client (invoker).
Since msbuild access console in serial fashion, this class was not originally written as thread safe. However, if custom code (tasks, logger and such) do call console flush directly it can interfere with logging service thread. Accessing console directly is not supported and customers shall avoid it. 
@MichalPavlik as an author of these particular lines, what is your take?
