### ISSUE TITLE
[NETSDKE2E]The error count displays incorrectly in output of dotnet test xunit.

### ISSUE THREAD

**Issue by vdanche** [dotnet/msbuild#10050]
### Issue Description

Build info:
9.0.100-preview.4.24221.5

The error account displays incorrectly in output of dotnet test xunit.

### Steps to Reproduce

In CLI: dotnet new xunit -o myxunit
add below codes
```
namespace myxunit;

public class UnitTest1
{
    [Fact]
    public void Test3()
    {

    }
    [Fact]
    public void Test1()
    {
Assert.Equal(12, 11);
    }
    [Fact]
    public void Test2()
    {
Assert.Equal(11, 11);
    }
}
```
dotnet test

### Expected Behavior

The log can be displayed well.

### Actual Behavior

The log displays "Build failed with 2 errors", but error and error VSTEST1 for test 1 method should be considered an error)
![image](https://github.com/dotnet/msbuild/assets/65637796/7a0493ca-624e-492e-855a-1fccc6605074)

8.0
![image](https://github.com/dotnet/msbuild/assets/65637796/065e4a96-a005-4e97-ad65-91597cb66182)

**Comment by v-xiaofchen** [comment]
This issue also repro on MacOS

**Comment by nohwnd** [comment]
This is not a bug, the failed test count is 1 which is correct. The number of errors in build is 2, because xunit reports their error, and we report the error from vstest, so there are 2. 

This is the same behavior as in the current execution without terminal logger: 

![image](https://github.com/dotnet/msbuild/assets/5735905/57876ddb-89da-44da-9682-ed23c7292a4d)

The highlighted message is **error** output that is sent by xunit.

**Comment by nohwnd** [comment]
I do agree it is confusing though because if there are only tests failing in the run, and no additional errors, then it is difficult to see why the counts don't agree.
