### ISSUE TITLE
Vet behavior change around StringCache removal

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#10465]
> Isn't this a change of behavior? StringCache.Add(text, this) just returned text, whereas this now interns the string? I don't think it will break anything, but I thought this PR was intended to have no effect as long as someone isn't disabling any change waves.

_Originally posted by @Forgind in https://github.com/dotnet/msbuild/pull/10404#discussion_r1684643279_

**Comment by AR-May** [comment]
This is intended change indeed. We (I and @rokonec as far as I remember) have decided to intern those strings instead of caching with project string cache. Even without interning the cache did not bring any value. So, adding interning should not be affecting anything but perf, and in a good way. If not, we will be able to catch it. The fact that we change the behavior is limiting in a way that change wave elimination PR is a feature now, but we can afford to merge them now, so it is ok.
