### ISSUE TITLE
[Bug]: MSB4184 while evaluating an expression in property setter

### ISSUE THREAD

**Issue by shadow-cs** [dotnet/msbuild#10583]
### Issue Description

Evaluating certain expressions causes `MSB4184`.

This is probably a regression from .NET 7 to .NET 8.

### Steps to Reproduce

```xml
<Project InitialTargets="Test">

  <Target Name="Test" >

    <PropertyGroup>
      <Foo>Foo</Foo>

      <!-- This has to be numeric. -->
      <Bar>1234</Bar>

      <!-- This is a workaround. -->
      <Good>$([System.String]::Equals($(Foo), $(Bar)))</Good>

      <!-- This works on .NET 7 but on 8 it doesn't. -->
      <Bad>$(Foo.Equals($(Bar)))</Bad>
    </PropertyGroup>

  </Target>
</Project>
```

### Expected Behavior

The expression to evaluate.

### Actual Behavior

For the given sample above I get:

```
error MSB4184: The expression ""Foo".Equals(1234)" cannot be evaluated. The input string 'Foo' was not in a correct format.
```

This is from my CI when I encountered this the first time:

```
error MSB4184: The expression """.Equals(2852592)" cannot be evaluated. The input string '' was not in a correct format.
```

### Analysis

The second operand (`Bar` in the example) needs to (most likely) be a number for this problem to appear.

Also converting to `$([System.String]::Equals(...))` mitigates the problem.

### Versions & Configurations

- My current MSBuild version: `17.11.0.32015`
- MSBuild version from my .NET 7 build container: `17.7.6.17813`
- MSBuild version from my .NET 8 build container: `17.11.4.40609`

**Comment by JanKrivanek** [comment]
@JaynieBai, @GangWang01 - can you please try to repro and look into reason for this?
Once understood - it should be discussed on some kitten sync how we want to proceed (documentation/fix)

**Comment by JaynieBai** [comment]
@JanKrivanek  this exception is since the following convert, The objectInstance is string "Foo" https://github.com/dotnet/msbuild/blob/b1e6c2512963d41949b5c8e287ca3bb4e9fa2e90/src/Build/Evaluation/Expander.cs#L3530C29-L3530C127

**Comment by JanKrivanek** [comment]
Thank you @JaynieBai!
This indeed looks as a regression from NET7 to 8. Since it's almost full year after release - it's not that high priority now (so feel free to prioritize NET9 work if needed), but let's work on fixing.

I'd ask you to please start with draft PR with couple unit test casess that demonstrates the behavior. They can be added e.g. here:

https://github.com/dotnet/msbuild/blob/b1e6c2512963d41949b5c8e287ca3bb4e9fa2e90/src/Build.UnitTests/Evaluation/Expander_Tests.cs#L4041-L4091

Then let's add this tikcet back to triage and team will decide about fixing.
