### ISSUE TITLE
[Broken Build]: Can not see the build message after upgrading from .net8 to .net9 RC1

### ISSUE THREAD

**Issue by ali50m** [dotnet/msbuild#10646]
### Issue Description

I used the following message system to output building information in .Net 8, it works well. But after upgrading to .net9 RC1 this morning, I find these message doesn't come out. 

```xml
  <Target Name="OutputMessage" AfterTargets="PostBuildEvent">
      <Message Importance="high" Text="build message..."/>
  </Target>
```

My question is, how to output this kind of building message in .Net9?

### Steps to Reproduce

update .net8 SDK to .net9 RC1 SDK

### Expected Behavior

can see the custom message when building in command line.

### Actual Behavior

cann't see the custom message when building in command line.

**Comment by baronfel** [comment]
Try with '-v d' - in .NET 9 the new Terminal Logger is more strict about what it shows by default so that build output is more readable to users. 

What was the intent of this message you were trying to show? Was it a status of some kind? Reporting some kind of build output? Something else entirely?
