### ISSUE TITLE
VS repo build broken by 17.13 MSBuild

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#11091]
VS builds are broken with a VS that contains #11000.

**Comment by JanKrivanek** [comment]
It's supper strange that `RespectAlreadyAssignedItemCulture` property set here:

https://dev.azure.com/devdiv/DevDiv/_git/VS/commit/aa9193b591f6a0fa9a355082718e95f963c94bf1?refName=refs/heads/dev/trevors/main/respectalready241204&path=/src/Xaml/Designer/Source/SurfaceExtensibility/Extensibility/SurfaceExtensibility.csproj

![Image](https://github.com/user-attachments/assets/35012282-2b65-4817-91fa-26c40e503dd9)

Is not reflected in the build at all (it doesn't show up neither in evaluation):

![Image](https://github.com/user-attachments/assets/a5a1870d-60bd-4d4b-a2a0-3d7c7fc92993)

**Comment by JanKrivanek** [comment]
As to the build error - the issue is that `_SatelliteAssemblyResourceInputs.Culture` metadata is being derefenced during `GenerateSatelliteAssemblies` call, while it's empty.

The  `_SatelliteAssemblyResourceInputs` is properly including only `EmbeddedResource` that has `WithCulture` set to true

https://github.com/dotnet/msbuild/blob/main/src/Tasks/Microsoft.Common.CurrentVersion.targets#L4008-L4038

And this metada is properly set by `AssignCulture`, but then for some reason changes after `CreateCSharpManifestResourceName` task (within `CreateManifestResourceNames` target) finishes and `GenerateResource` task (in `CoreResGen` target) starts - despite there is no appearant msbuild logic touching it:


![Image](https://github.com/user-attachments/assets/42a197fd-a634-4a73-b92f-815079cd6c85)


Debugging this through now..

**Comment by JanKrivanek** [comment]
Conclusion:

* Custom VS build internal target is flipping the `WithCulture` metadata: https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/Xaml/Shared/Tools/BuildTargets/SdkStyle.targets&version=GBmain&line=61&lineEnd=87&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents
* This is properly solvable with the `RespectAlreadyAssignedItemCulture` property suggested by the new warning.
* I can repro the case and the `RespectAlreadyAssignedItemCulture` fixing it. We need to investigate why it did not propagate properly in the VS build

**Comment by JanKrivanek** [comment]
It turns out that DartLab is building VS from main, not current branch - that was the reason why the property wasn't reflected.
When customizing pipeline to build VS from current branch - all succeeds just fine: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=10699017&view=results

**Comment by adrianoc** [comment]
Hi, at Unity we are observing this error in our CI jobs from time to time; unfortunately we cannot update to version [17.13.9](https://www.nuget.org/packages/Microsoft.Build/17.13.9) (which includes the fix) because our build runs on .NET 8.

Is there any chance for this fix to be included in a version of the nuget package that supports .NET 8.0 ?

**Comment by rainersigwald** [comment]
@adrianoc 17.13.9 _introduced_ this bug. Can you file a new issue describing the problem you're seeing and why you think it's related?

**Comment by adrianoc** [comment]
my bad. The bug we are observing is [this one](https://github.com/dotnet/msbuild/issues/10753).
I'll post there, sorry for the noise.
