### ISSUE TITLE
msbuild fails to load task assembly if there is one right next to msbuild.dll

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/msbuild#1690]
if there are more than one copy of the task dll, and the targets file refer to a copy that is not right next to msbuild.dll , msbuild crashses with an error like : 

``` 
error MSB4062: The "NuGet.Build.Tasks.Pack.PackTask" task could not be loaded from the assembly C:\Users\ragrawal\AppData\Local\Temp\NuGetTestFolder\4e25a2f6-7075-442c-bafe-7f9a473cf069\sdk\1.0.0-rc4-004777\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\..\CoreCLR\NuGet.Build.Tasks.Pack.dll. Could not load file or assembly 'NuGet.Build.Tasks.Pack, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. 

```

CC: @rainersigwald

**Comment by rainersigwald** [comment]
This one was _deeply_ mysterious! I was able to confirm the problem by observing a failure with ProcMon and seeing that a load was attempted from next to `dotnet.exe` instead of `MSBuild.dll` as you'd expect.

This happens because MSBuild has [logic to simulate `LoadFrom` in CoreCLR](https://github.com/rainersigwald/msbuild/blob/99e95d0f55d2af82767ffd8c81dcfdc663092e49/src/Shared/TypeLoader.cs#L187-L204).

In this case, MSBuild observed that there was a file named `NuGet.Build.Tasks.Pack.dll` in the `CurrentMSBuildToolsDirectory`, so it attempted to load using a bare `Assembly.Load` of `"NuGet.Build.Tasks.Pack"`. The CLR loader then probes

```
3:55:51.7967062 PM	dotnet.exe	16088	QueryOpen	S:\work\rohit-usingtask-failure\cli.1.0.0-rc4-4777\sdk\1.0.0-rc4-004777\Sdks\Microsoft.NET.Sdk\tools\netcoreapp1.0\NuGet.Build.Tasks.Pack.ni.dll	NAME NOT FOUND	
3:55:51.7969958 PM	dotnet.exe	16088	QueryOpen	S:\work\rohit-usingtask-failure\cli.1.0.0-rc4-4777\sdk\1.0.0-rc4-004777\Sdks\Microsoft.NET.Sdk\tools\netcoreapp1.0\NuGet.Build.Tasks.Pack.ni.exe	NAME NOT FOUND	
3:55:51.7972648 PM	dotnet.exe	16088	QueryOpen	S:\work\rohit-usingtask-failure\cli.1.0.0-rc4-4777\sdk\1.0.0-rc4-004777\Sdks\Microsoft.NET.Sdk\tools\netcoreapp1.0\NuGet.Build.Tasks.Pack.dll	NAME NOT FOUND	
3:55:51.7974816 PM	dotnet.exe	16088	QueryOpen	S:\work\rohit-usingtask-failure\cli.1.0.0-rc4-4777\sdk\1.0.0-rc4-004777\Sdks\Microsoft.NET.Sdk\tools\netcoreapp1.0\NuGet.Build.Tasks.Pack.exe	NAME NOT FOUND	
```

And doesn't find it in any of those places.

It looks like our assumption that `Assembly.Load` would look next to MSBuild is wrong . . . somehow.

It should be rare to try to load a task from a DLL in the MSBuild bin folder outside of our own tasks, which work for other reasons (evidently‽), so this doesn't seem too bad.
