### ISSUE TITLE
File.cs.cshtml cannot become EmbeddedResource

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/msbuild#3064]
_From @davkean on March 5, 2018 22:43_

_From @abpiskunov on March 2, 2018 6:17_

1. Create a new core Web app
2. in File Explorer find some cshtml page (Error.cshtml and rename it to Error.cs.cshtml.
3. In VS change type of Error.cs.cshtml to EmbeddedResource (notice it will be removed from Content in csproj)
4. Build
5. Open assembly manifest and see - no embedded resources
6. When rename file to Error.cshtml , build, assembly manifest does contain EmbeddedResource.

See this issue opened by customer originally : https://github.com/aspnet/Tooling/issues/1066#issuecomment-369131680 

_Copied from original issue: dotnet/project-system#3336_

_Copied from original issue: dotnet/sdk#2024_

**Comment by dsplaisted** [comment]
_From @davkean on March 5, 2018 22:43_

This would be a build issue, no?

**Comment by dsplaisted** [comment]
_From @davkean on March 5, 2018 22:43_

_From @abpiskunov on March 2, 2018 16:51_

Sounds like that or even could be sdk related, Content item type might somehow interfere with EmbeddedResource.

**Comment by dsplaisted** [comment]
_From @davkean on March 5, 2018 22:43_

_From @Pilchie on March 2, 2018 19:43_

@livarcocc @nguerrera @dsplaisted ?

**Comment by dsplaisted** [comment]
_From @davkean on March 5, 2018 22:43_

_From @nguerrera on March 2, 2018 20:38_

Could be sdk or msbuild. Feel free to move to sdk for next look.

**Comment by dsplaisted** [comment]
_From @davkean on March 5, 2018 22:43_

_From @dsplaisted on March 2, 2018 20:40_

I want to take a look at this, but I suspect it is CPS not understanding how to modify the project to change the item type given the default globs that the project has.

**Comment by dsplaisted** [comment]
_From @davkean on March 5, 2018 22:43_

_From @abpiskunov on March 2, 2018 21:56_

we have a vs feedback bug associated with that 574198. Who should i assign to? Who is doing first investigation here?

**Comment by dsplaisted** [comment]
_From @davkean on March 5, 2018 22:43_

_From @abpiskunov on March 5, 2018 20:7_

Ok i am assigning the bug to Daniel first. Please route it further if it is not yours.

**Comment by dsplaisted** [comment]
It turns out the issue here is that MSBuild (via the `AssignCulture` task) thinks that an `EmbeddedResource` with a name of `Error.cs.cshtml` is a Culture-specific resource for the `cs` culture.  So ends up going in the satellite assembly for `cs`.

Related suggestion from @nguerrera: https://github.com/Microsoft/msbuild/issues/1454#issuecomment-265621913

> Another approach would be to respect explicit WithCulture metadata as implying that no check is required.

This would let you explicitly turn this off if you don't want it.

**Comment by sandrock** [comment]
I have the same issue on my side. It looks like the [one](https://github.com/aspnet/Tooling/issues/1066) @rjamesnw posted. Some files get put into a satellite assembly because a part of the file name looks like a culture name. 

I would like to the `AssignCulture` task to skip the file. The related issue #1454 is about *forcing* the task to assign a culture. I wish to do the *opposite*: preventing the task from executing.

Is there a workaround available?

**Comment by rainersigwald** [comment]
I was optimistic about this but it didn't quite work

## Incomplete workaround

```xml
  <Target Name="WorkaroundMSBuild3064" BeforeTargets="SplitResourcesByCulture">
    <!-- Workaround for https://github.com/Microsoft/msbuild/issues/3064 -->
    <ItemGroup>
      <_ResourcesWithCultureFilename Include="@(EmbeddedResource)" Condition="$([System.String]::Copy('%(Filename)').Contains('.cs'))" />

      <_MixedResourceWithNoCulture Include="@(_ResourcesWithCultureFilename)">
        <WithCulture>false</WithCulture>
      </_MixedResourceWithNoCulture>

      <EmbeddedResource Remove="@(_ResourcesWithCultureFilename)" />
    </ItemGroup>
  </Target>
```

It doesn't work because the `CreateManifestResourceNames` target calls `CreateCSharpManifestResourceName` which does its own independent rediscovery of culture, mangling it to, for example, `ManifestResourceName = cs\3064.Views.Home.About.cshtml`.

_That_ could be avoided by explicitly specifying a `ManifestResourceName`, but I can't think of a good way to do the transform automatically--that's why it's done in a task in the first place.

A full solution would need to address the `CreateCSharpManifestResourceName` culture-discovery problem too.

**Comment by BenVillalobos** [comment]
Related feedback tickets:
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1228576
https://dev.azure.com/devdiv/DevDiv/_queries/edit/1115155/?triage=true

**Comment by ahdung** [comment]
same issue, for me, the bad file name is `Resources.en.xml` or `Resources.zh.xml`.
