### ISSUE TITLE
RAR: refactor AssemblySearchPaths to allow turning off individual locations

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#3784]
Right now AssemblySearchPaths uses string concatenation and is hard to modify. We should refactor it so that it's easy to turn off individual locations.

Maybe have an item, and collapse it to a property at the end? But what to do about evaluation passes (properties before items)...

**Comment by rainersigwald** [comment]
I don't think moving to an item is a good option, because of the ordering you mentioned and the possibility of existing user customization of the property, which would be confusing if it was radically restructured.

We've thought about having boolean properties for each entry, so they can be disabled individually, something like `$(ResolveAssemblyReferenceAllowGAC)`.

Since the default is defined in .targets

https://github.com/Microsoft/msbuild/blob/48874c3f3d5e29dbecf30be33a7cd00bffde1038/src/Tasks/Microsoft.Common.CurrentVersion.targets#L560-L571

it's reasonably ergonomic to define properties in the project file (or a `Directory.Build.props`).

If we do this, we should also provide an easy-to-opt-into "good" set of defaults that excludes machine-wide locations. Then we can recommend new projects opt into that.

**Comment by rainersigwald** [comment]
See also dotnet/msbuild#772, which may be a superset of this.
