### ISSUE TITLE
Update .editorconfig

### ISSUE THREAD

**Issue by CodeTherapist** [dotnet/msbuild#4092]
Update the [.editorconfig](https://github.com/Microsoft/msbuild/blob/master/.editorconfig) with additional rules.

**Advantages** 
* keeps the code format as defined - regardless who is contributing
* reduces PR review complexity (code formatting changes are gone)
* works for common IDE's

- [ ] Define a standard
- [ ] Extend the existing file
- [ ] Reformat solution

**Comment by rainersigwald** [comment]
We have one (untouched in 4 years), but it'd be quite reasonable to bring it up to date using the steps here.

**Comment by rainersigwald** [comment]
Yeah, that sounds good to me. We may want to eventually standardize more with what corefx or roslyn are doing, but that can be an incremental move, if necessary.

One wrinkle I can think of: this repo has a few bits of code forked from other places. For ease of updating, those shouldn't be formatted to our conventions, but left as they were--otherwise the diffs resulting from taking a new upstream are confusing and awful. We should drop empty `.editorconfig` files in those directories.

**Comment by Pilchie** [comment]
> We should drop empty `.editorconfig` files in those directories.

Editorconfig automatically chains, so instead, drop a `.editorconfig` with `root=true`.

**Comment by rainersigwald** [comment]
@livarcocc Should we think about having a standard for all of our repos and applying that here? If we don't want to push for that, I think the generate-one-from-current-usage approach sounds nice.

**Comment by Pilchie** [comment]
Most of the `dotnet` repos are fairly consistent already.  @jaredpar, @stoub, etc did some work to come up with https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

**Comment by rainersigwald** [comment]
Yeah, and we shouldn't be too far off from that--at the dawn of time we used codeformatter on this repo. Just haven't been keeping up with it recently.

**Comment by livarcocc** [comment]
@rainersigwald I have been thinking about having one that's common for our whole team for a while. Feel free to drive that.
