### ISSUE TITLE
Fail build on double write

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/msbuild#4524]
@davkean fixed a double write issue in the project system today (https://github.com/dotnet/project-system/pull/5080).

We'd like to have a way to fail our build if a double write is reintroduced.

Is this possible, and if not, what would it take to add this?

**Comment by drewnoakes** [comment]
@jmarolf [points out](https://github.com/dotnet/project-system/issues/4802#issuecomment-512881703):

> Roslyn uses a tool called [BuildBoss](https://github.com/dotnet/roslyn/tree/master/src/Tools/BuildBoss) which reads the binlog after a build and fails if there is a double-write

**Comment by JustinSchneiderPBI** [comment]
Yes. Even BuildBoss didn't work sufficiently for us, since we have a large backlog of doublewrites to work through. I wrote a similar tool reading binlogs that supports a baseline of the current issues to protect from regressions and new instances. Hope to add it in a more general form to one of Kirill's build tools later this year.

**Comment by maridematte** [comment]
We have implemented a Check for detecting double writes that you can use, [it is BC0102](https://github.com/dotnet/msbuild/blob/e5669f0208fdb25e72e7f00e93758f656c1462c1/documentation/specs/BuildCheck/Codes.md#buildcheck-reports-codes-and-their-meaning).

**Comment by JustinSchneiderPBI** [comment]
So excited!! Thank you!
