### ISSUE TITLE
AfterTargets relationship is not respected between two targets if both specify same BeforeTargets

### ISSUE THREAD

**Issue by Lizzy-Gallagher** [dotnet/msbuild#4712]
### Steps to reproduce

See 
[AfterBuildBugRepro.zip](https://github.com/microsoft/msbuild/files/3597470/AfterBuildBugRepro.zip)

Relevant part of the project file
```xml
<Project>
    <Target Name="DoSomething" AfterTargets="SetUpStep" BeforeTargets="BeforeBuild">
        <Message Text="DoSomething" />
    </Target>

    <Target Name="SetUpStep" BeforeTargets="BeforeBuild">
        <Message Text="SetUpStep" />
    </Target>
</Project>
```

### Expected  behavior
```
SetUpStep
DoSomething
```
### Actual behavior
```
DoSomething
SetUpStep
```

### Environment data
`msbuild /version` output:
```
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.9.21.664
```

`dotnet  --version` output:
2.2.107

I have attempted to change the BeforeTargets to other targets and the same bug persists. This is a simplification of something else I am trying to do -- have an AfterBuild dependency on a "set up" target that may or may not exist, depending on whether a NuGet package is installed. The repro above gets at the issue by putting the "set up" target and the "do something" target in the same project.

**Comment by livarcocc** [comment]
@dsplaisted can you help here?

**Comment by Bartleby2718** [comment]
@dsplaisted Seems like this wasn't triaged. Could you have someone look into this?

**Comment by rainersigwald** [comment]
This is by design. `AfterTargets` does not introduce an ordering dependency; `<Target Name="X" AfterTargets="Y"` means "if Y executes, run X after it". If something else causes Y to run first, it will not be run again.

The ordering between two targets that `AfterTargets` or `BeforeTargets` the same target is not specified and should not be relied on.

To establish a "prerequisite" target for a given target, use `DependsOnTargets`.
