### ISSUE TITLE
MSBuild <Exec>/ToolTask resets the console output code page, prohibiting unicode output

### ISSUE THREAD

**Issue by tristanlabelle** [dotnet/msbuild#4870]
### Steps to reproduce

Repro project (save as `repro.proj`):
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="Print">
        <Exec Command="chcp" />
    </Target>       
</Project>
```

Repro commands in `cmd.exe`:
```
>chcp
Active code page: 850

>msbuild repro.proj
Microsoft (R) Build Engine version 16.4.0-preview-19517-01+31c846a51 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 11/1/2019 8:35:23 AM.
Project "repro.proj" on node 1 (default targets).
Print:
  chcp
  Active code page: 850
Done Building Project "repro.proj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.18

>chcp 65001
Active code page: 65001

>msbuild repro.proj
Microsoft (R) Build Engine version 16.4.0-preview-19517-01+31c846a51 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 11/1/2019 8:35:29 AM.
Project "repro.proj" on node 1 (default targets).
Print:
  chcp
  Active code page: 850
Done Building Project "repro.proj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.23
```

Note: 850 is the Western Europe/US code page, representing most latin-based characters. 65001 is UTF-8, which can represent all Unicode characters.

### Expected  behavior
When run inside MSBuild, `chcp` should output the same code page as its ancestor `cmd.exe`.

Programs should inherit the console code page from their ancestors.

### Actual behavior
When run inside MSBuild, `chcp` outputs 850 rather than 65001 as set on the ancestor `cmd.exe`.

MSBuild's `<Exec>` task executes its commands in such a way that the child processes do not inherit the console code page from MSBuild (which itself inherited it from its parent). The console code page for children processes is rather reset to the OEM code page, which cannot encode Unicode characters in any Windows OS language in its default configuration. This means that it is impossible to use MSBuild to run a program that will output Japanese characters on an English OS without it coming out as a bunch of `?????`.

Specifically, the use of `ProcessStartInfo.CreateNoWindow = true` in `ToolTask` will reset the console code page of the child process to the OEM code page. If this is fixed, the batch file should also be written in the console code page since that is what `cmd.exe` will be using to read it. Pull request coming soon.

### Environment data
`msbuild /version` output: `Microsoft (R) Build Engine version 16.4.0-preview-19517-01+31c846a51 for .NET Framework`
OS info: Windows 10

**Comment by MrTrillian** [comment]
If `ProcessStartInfo.CreateNoWindow` cannot be set to `false` for other reason. There is an alternative, contrived solution that would work:

MSBuild could prepend $"chcp {Console.OutputEncoding.CodePage}\r\n" to the batch file and write the batch with the encoding from `Console.OutputEncoding`. `cmd.exe` would be started with OEM as its console code page due to `CreateNoWindow`. However, after executing the first line of the batch file, it would switch to the same console output code page as MSBuild, essentially reimplementing inheritance. The following lines of the batch file would then also be decoded using the `Console.OutputEncoding` code page (yes, `cmd.exe` is that horrible), hence why it is necessary to encode the batch file itself in that encoding. MSBuild would have to set `ProcessStartInfo.StandardOutputEncoding = Console.OutputEncoding` in order to decode the commands' output using the console output code page that they should be honoring.

**Comment by MrTrillian** [comment]
Note that `<PostBuildEvent>` is implemented in terms of `<Exec>`, so it is also subject to this issue.

**Comment by Akarinnnnn** [comment]
Maybe we should have an parameter indicates that is sub-process produces Unicode output. Consider most of dotnet commands (even MGCB) uses Unicode, this option should have a true value in default.

**Comment by ThisFunctionalTom** [comment]
Hi,

I have the same/similar problem.

The output of Exec task is not shown correctly.

Here are some simple steps to reproduce it.

1. Create `output.cmd` file with following content
  ```output.cmd
  echo ✓ 54 modules transformed.
  ```

2. Create a simple project file with following target
  ```csproj
  <Target Name="OutputSomething" BeforeTargets="BeforeBuild">
    <Message Text="✓ 54 modules transformed." Importance="high" />
    <Exec Command="echo ✓ 54 modules transformed." />
    <Exec Command="cmd /c echo ✓ 54 modules transformed." />
    <Exec Command="output.cmd" />
    <Exec Command="output.cmd" UseUtf8Encoding="true" />
    <Exec Command="output.cmd" ConsoleToMSBuild="true">
      <Output TaskParameter="ConsoleOutput" PropertyName="OutputOfExec" />
    </Exec>
    <Exec Command="cmd /c output.cmd" />
  </Target>
  ```

3. Run `dotnet build` and get following output
  ```cmd
  Determining projects to restore...
  All projects are up-to-date for restore.
  ✓ 54 modules transformed.
  ✓ 54 modules transformed.
  ✓ 54 modules transformed.
  Ô£ô 54 modules transformed.
  Ô£ô 54 modules transformed.
  Ô£ô 54 modules transformed.

  C:\Users\leko.tomas\playground\TestMsBuildOutput>echo Ô£ô 54 modules transformed.
  Ô£ô 54 modules transformed.
  ```

I guess that there is some problem when starting a script file (cmd or powershell). If the command is written directly in `Command` attribute everything works fine.

**Comment by rainersigwald** [comment]
> Maybe we should have an parameter indicates that is sub-process produces Unicode output.

That's `UseUtf8Encoding="Always"`.

> Consider most of dotnet commands (even MGCB) uses Unicode, this option should have a true value in default.

This is a pretty breaky change since most _Windows_ commands and most Windows tools don't emit Unicode, so we haven't done it.

@ThisFunctionalTom `UseUtf8Encoding="true"` is ignored; [valid values are are `Always`, `Never`, or `Detect`](https://learn.microsoft.com/en-us/visualstudio/msbuild/exec-task?view=vs-2022#:~:text=Valid%20values%20are%20Always%2C%20Never%2C%20or%20Detect.). We should probably treat `true` as `Always` though, since it isn't currently an error.
