### ISSUE TITLE
Detect OS architecture

### ISSUE THREAD

**Issue by lijunle** [dotnet/msbuild#5065]
Related to this: https://github.com/microsoft/msbuild/issues/2468 , but for [OS architecture](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.osarchitecture?view=netframework-4.8#System_Runtime_InteropServices_RuntimeInformation_OSArchitecture) (X86/X64).

Currently, I have the following code as a workaround:

```xml
<Runtime Condition=" $([MSBuild]::IsOsPlatform('Windows')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64' ">win-x64</Runtime>
<Runtime Condition=" $([MSBuild]::IsOsPlatform('Windows')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X86' ">win-x86</Runtime>
```

It could better to have `$([MSBuild]::IsOsArchitecture('X86'))` method available.

/cc @rainersigwald

**Comment by rainersigwald** [comment]
Can you elaborate on why you want to do this? In your example, why do you want to control the output you're building based on the architecture of the MSBuild process that's building it? In general, any MSBuild architecture should be able to produce any output architecture.

**Comment by lijunle** [comment]
It is a dev-tool to run on all OSes. In NuGet package, there are 4 binaries shipped - for win-x64, win-x86, macOS, Linux. When the MSBuild targets is invoked, it needs to select the correct binary based on the current OS and architecture.

**Comment by oakad** [comment]
In general, now that dotnet core is multiplatform, it can be very handy to be able to define build constants and other such things based on the target platform/arch. All proper multiplatform build systems offer such capability.

Of course, this is only useful in code which interacts with unmanaged/native libraries, but such libraries are plentiful and the need to use them arises rather often.

**Comment by glen-84** [comment]
@rainersigwald 

Could this be reopened?

I'd like to conditionally install NuGet packages based on the OS architecture, and a shorter condition would be nice. 🙂

**Comment by rainersigwald** [comment]
> I'd like to conditionally install NuGet packages based on the OS architecture

That sounds unusual to me. You want to install different NuGet packages depending on the OS of the build machine, rather than the target?

**Comment by oakad** [comment]
I will simply leave this here: https://wiki.osdev.org/Target_Triplet :-)

**Comment by glen-84** [comment]
I don't understand how that relates to my question.

**Comment by glen-84** [comment]
@rainersigwald Are you able to assist with the above question?

**Comment by perlun** [comment]
I understand this requirement, but I think that what people is probably really asking for is "detect _target_ OS architecture" most of the time? :thinking: @rainersigwald is correct in questioning "why detect the runtime architecture of MSBuild" since that's typically the "wrong question" I think. But it would still be nice with an example of detecting the OS that the MSBuild process is currently targeting. :slightly_smiling_face: 

After some (well, quite a lot) of experimenting I ended up with something like this:

```csproj
<PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('linux')) Or $(NETCoreSdkPortableRuntimeIdentifier.StartsWith('linux'))">
  <DefineConstants>$(DefineConstants);_LINUX</DefineConstants>
</PropertyGroup>

<PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('win')) Or $(NETCoreSdkPortableRuntimeIdentifier.StartsWith('win'))">
  <DefineConstants>$(DefineConstants);_WINDOWS</DefineConstants>
</PropertyGroup>
```

Putting the above in my `Directory.Build.props` didn't work, but putting them straight in the relevant `.csproj` file worked fine. `Directory.Build.targets` also worked, so I'm guessing something (inside or outside of my solution) is overwriting the `DefineConstants` setting on the way if I put it in `Directory.Build.props` (which, as I understand it from https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-by-directory?view=vs-2022&source=recommendations#import-order, is imported quite early in the build processing).

**Comment by glen-84** [comment]
@perlun That's only checking the OS, not the architecture.

@rainersigwald Why was an issue with 9 up-votes closed without explanation?

**Comment by perlun** [comment]
> @perlun That's only checking the OS, not the architecture.

@glen-84 Yeah, good point. You should be able to adjust it by doing something like `RuntimeIdentifier.Contains('x64')` or similar (note, untested). Could that work?

**Comment by perlun** [comment]
(btw, I edited my version of the MSBuild `<PropertyGroup>` now after debugging it since we found out that the original version didn't work. `NETCoreSdkPortableRuntimeIdentifier` seems to be set to `linux-x64` even when doing `-r win-x64` in the `dotnet publish` command line. This seems like a bug to me, I don't know if it's reported anywhere. :thinking:)

**Comment by glen-84** [comment]
> @glen-84 Yeah, good point. You should be able to adjust it by doing something like `RuntimeIdentifier.Contains('x64')` or similar (note, untested). Could that work?

`RuntimeIdentifier` is empty for me. As far as I know, this value is [set by the developer](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#runtimeidentifier).

**Comment by doubleyewdee** [comment]
Sad this is closed because I also need this. The VS threading analyzer is super buggy on Apple Silicon and I just want to turn it off locally for people on this hardware. I understand that 99% of the time you care about the target platform/CPU architecture, but sometimes the host architecture is more important.
