### ISSUE TITLE
How to make preprocessor condition work with project name in Shared Project?

### ISSUE THREAD

**Issue by Denis535** [dotnet/msbuild#5096]
I'm sorry if this is not the right place for my question, but I have spent a few days and no result.
Shared project is cool thing. And it's cool that shared code can know types from normal projects. But sometimes it leads to: missing type error. 
So the question is: can I make `ConditionalAttribute` or `#if - #endif` to exclude some code for some projects?

**Comment by Deni35** [comment]
Okey, I made `Directory.Build.targets` with next code. 
Due to error: `The reference to custom metadata “PackageReference” at position 2 is not allowed in this condition` I can't do condition with batching outside of `Target`. 
So, I put it within target invoking after `PrepareForBuild`.

```
<Project>

  <Target Name="DefineConstants" AfterTargets="PrepareForBuild">
    <PropertyGroup>
      <DefineConstants>$(DefineConstants);$(MSBuildProjectName.Replace('.', '_'))</DefineConstants>
      <DefineConstants Condition=" '%(PackageReference.Identity)' == 'nunit' ">$(DefineConstants);NUnit</DefineConstants>
    </PropertyGroup>
  </Target>

  <Target Name="PrintInfo" AfterTargets="DefineConstants">
    <Message Text="========== ========== ========== ========== ========== ========== ========== ==========" Importance="high" />
    <Message Text="ProjectName: $(MSBuildProjectName)" Importance="high" />
    <Message Text="PackageReferences: @(PackageReference)" Importance="high" />
    <Message Text="DefineConstants: $(DefineConstants)" Importance="high" />
    <Message Text="========== ========== ========== ========== ========== ========== ========== ==========" Importance="high" />
  </Target>

</Project>

```

I'm not sure whether I'm right or not. But looks like it works. 
P.S. Anybody knows what is that error means?
P.P.S. Looks like Visual Studio has a bug. Content of `#if NUnit ... #endif` is always shadowed. But there is no errors and building works. Don't know why. Maybe because this content is used only by test projects.
P.P.P.S. MSBuild is really hell))

**Comment by dsplaisted** [comment]
Instead of debugging by adding targets to print out information, try creating binary logs and using MSBuild Structured Log Viewer to inspect them.  See here: http://msbuildlog.com/
