### ISSUE TITLE
Please add `$(MSBuildThisFile)` implicitly to any Target's `Inputs=""`

### ISSUE THREAD

**Issue by otac0n** [dotnet/msbuild#5472]
### Steps to reproduce

In the sample here, I restore NPM based on the filetime of the `.msbuild` file in the `node_modules` folder.  However, if I add additional authentication logic to the target, the target is not re-run.

Project file
```xml
<Project DefaultTargets="...">
  ...
  <Target Name="NpmRestore" DependsOnTargets="EnsureNpm" Inputs="package.json" Outputs="node_modules\.msbuild">
    <!-- A change made here, (e.g. to enable certain authentication mechanisms) would not be automatically picked up. -->
    <Exec Command="$(NpmCommand) install" IgnoreStandardErrorWarningFormat="true" />
    <Touch Files="node_modules\.msbuild" AlwaysCreate="true" />
  </Target>
  ...
</Project>
```

Directory contents:
```
/
- package.json
- package-lock.json
- msbuildthistarget.targets
- node_modules/
     - .msbuild
     - wow... uh... 300mb that I don't want to log here.
```

Command line
```
msbuild
```
### Expected behavior

After changing the `msbuildthistarget.targets` file, the `NpmRestore` target would be executed.

### Actual behavior

Incremental build detects that no inputs have changed.  When the literal text of the target or the context has changed, the target should be re-run.  If that's too complicated, $(MSBuildThisFile) would be--generally--an efficient stand-in.

### Environment data
`msbuild /version` output: (all versions)

OS info: Windows 10

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
cmd.exe

**Comment by otac0n** [comment]
This in fact has better incremental behavior than a simple rebuild, and also follows the "principle of least surprise" in my opinion.

**Comment by rainersigwald** [comment]
You can always do this yourself. In fact, you should consider using `$(MSBuildAllProjects)`, instead of `$(MSBuildThisFile)`, so that you pick up changes made in imported files like `Directory.Build.targets`.

The engine could do it, but that would be fairly inefficient--for instance, a change you made to your target would cause all other targets to rerun, regardless of whether _their_ inputs changed.

This is a weakness of the MSBuild incrementality model. The overall issue for that is #2470.
