### ISSUE TITLE
Announcement: Repo move to dotnet org

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/msbuild#5523]
Early next week, we are planning to move this repository to `dotnet/msbuild` as part of some maintenance activities of .NET Foundation projects. There should be no impact on forks or links as GitHub will redirect them to the new location.

Please let us know if you have any concerns!

**Comment by KathleenDollard** [comment]
Just wanted to add some clarity about why we are moving the MSBuild GitHub repo to the the dotnet organization: 

* MSBuild is written in .NET and a large chunk of its features are rooted deeply in the .NET ecosystem
* Most consumers & contributors are from the .NET ecosystem
* It’s been a .NET Foundation project since 2017so the dotnet org is a logical location

We know that that folks use MSBuild for things other than .NET. The move to the .NET Foundation does not represent any change in focus C++ remains a first class citizen for MSBuild. 

The new link will be `https://github.com/dotnet/msbuild`

Kathleen Dollard
MSBuild PM

**Comment by Nirmal4G** [comment]
This is nice. One QQ though, will the name remain **`MS`**`Build`?

**Comment by Kryptos-FR** [comment]
@Nirmal4G Maybe `dotbuild` or just `build`. At least the repo could be named `https://github.com/dotnet/build` even if the executable retains the `MS`prefix for a while.

**Comment by Nirmal4G** [comment]
I propose `xbuild` 😇, then again, it's fairly a common name, might already been taken so...🙃

**Comment by rainersigwald** [comment]
This is complete (and builds and insertions to VS are back up and running).
