### ISSUE TITLE
UsingTask overrides do not apply if newly specifying Architecture/Runtime

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#5541]
In this case:

```xml
  <UsingTask TaskName="VSCTCompiler" AssemblyFile="$(VsSDKAssemblyFile)" Architecture="x86" />
  <UsingTask TaskName="VSCTCompiler" AssemblyFile="$(VsSDKAssemblyFile)" />
```

I _expected_ that the first UsingTask would be used, and require a 32-bit TaskHost if running on a 64-bit MSBuild. But it is not, because internally we look tasks up based on the task's "identity parameters" (runtime/arch) as defined _at the callsite_:

https://github.com/dotnet/msbuild/blob/e8338f5ad91d42c3196218648859e9e837099842/src/Build/Instance/TaskRegistry.cs#L470

If the callsite doesn't specify (as most don't), the no-arch-specified UsingTask entry is a "better match" for the request and is used.

This means that a user can't override a UsingTask that's specified in a NuGet package or SDK to specify an architecture to work around a bug in the package/sdk that the task is secretly x86-specific.

**Comment by rainersigwald** [comment]
Because of 64-bit VS this is likely to be more relevant, pulling into 17.0 for consideration.

**Comment by rainersigwald** [comment]
One note: there's a `.overridetasks` file next to MSBuild, for example on my machine

```
C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.overridetasks
```

This is intended to allow overriding task definitions. Since it requires changing the "installed"/"owned by VS" file it's not a great option and I think we should still fix this, but it's something to keep in our pocket.

Note that I didn't actually validate that this works . . .

**Comment by BenVillalobos** [comment]
Haven't done a deep dive yet, here's a lot of thinking out loud based on first glance:

The scenario is this:

1. User creates a UsingTask for task `Foo` as normal -> it gets added to the TaskRegistry.
2. User may create a more specific UsingTask for `Foo` (to use an x86 task specifically), also added to the registry.
	- Presumably they have a "global" using task, then a project specifies they want the x86 version of that task?
3. At build time, when we find task `Foo` to call and need to find it, we look into the registry BUT return the wrong one.
	-. What made it the wrong one? Did it pull up the first one it saw? "most compatible", in other words "less specific"?
	-. Looks like this is controlled at `GetTaskRegistrationRecord`


> I expected that the first UsingTask would be used, and require a 32-bit TaskHost if running on a 64-bit MSBuild

Why? Because it was the first one defined? Because it is more specific? I'm trying to reason about what the task registry should prefer when returning one task registration over another.

Shouldn't this sort of thing be determined based on a condition within the project anyway? A project should be able to tell "when I'm x86, use the x86 version of this task?" Probably because usingtask is a top level element, blarg.

How worried about breaking existing projects do we need to be here? This is the first I've seen of multiple UsingTask's on the same dll, and it sounds like defaulting to a different usingtask could break people.

This looks like the most relevant method:

```c#

        /// <summary>
        /// Retrieves the task registration record for the specified task.
        /// </summary>
        /// <param name="taskName">The name of the task to retrieve.</param>
        /// <param name="taskProjectFile">The task's project file.</param>
        /// <param name="taskIdentityParameters">The set of task identity parameters to be used to identify the
        /// correct task record match.</param>
        /// <param name="exactMatchRequired">True if an exact name match is required.</param>
        /// <param name="targetLoggingContext">The logging context.</param>
        /// <param name="elementLocation">The location of the task element in the project file.</param>
        /// <param name="retrievedFromCache">True if the record was retrieved from the cache.</param>
        /// <returns>The task registration record, or null if none was found.</returns>
        internal RegisteredTaskRecord GetTaskRegistrationRecord
            (
            string taskName,
            string taskProjectFile,
            IDictionary<string, string> taskIdentityParameters,
            bool exactMatchRequired,
            TargetLoggingContext targetLoggingContext,
            ElementLocation elementLocation,
            out bool retrievedFromCache
            )
```

**Comment by BenVillalobos** [comment]
I see the inherent problem here. Here's the summary of `FindTaskInRegistry` (`TaskExecutionHost.cs`)

```
/// Given the task name, this method tries to find the task. It uses the following search order:
/// 1) checks the tasks declared by the project, searching by exact name and task identity parameters
/// 2) checks the global task declarations (in *.TASKS in MSbuild bin dir), searching by exact name and task identity parameters
/// 3) checks the tasks declared by the project, searching by fuzzy match (missing namespace, etc.) and task identity parameters
/// 4) checks the global task declarations (in *.TASKS in MSbuild bin dir), searching by fuzzy match (missing namespace, etc.) and task identity parameters
/// 5) 1-4 again in order without the task identity parameters, to gather additional information for the user (if the task identity 
///    parameters don't match, it is an error, but at least we can return them a more useful error in this case than just "could not 
///    find task")

/// The search ordering is meant to reduce the number of assemblies we scan, because loading assemblies can be expensive.
/// The tasks and assemblies declared by the project are scanned first, on the assumption that if the project declared
/// them, they are likely used.
/// 
/// If the set of task identity parameters are defined, only tasks that match that identity are chosen. 
/// </summary>
/// <returns>The Type of the task, or null if it was not found.</returns>
        private TaskFactoryWrapper FindTaskInRegistry(IDictionary<string, string> taskIdentityParameters)
        {
            if (!_intrinsicTasks.TryGetValue(_taskName, out TaskFactoryWrapper returnClass))
            {
                returnClass = _projectInstance.TaskRegistry.GetRegisteredTask(_taskName, null, taskIdentityParameters, true /* exact match */, _targetLoggingContext, _taskLocation);
                if (returnClass == null)
                {
                    returnClass = _projectInstance.TaskRegistry.GetRegisteredTask(_taskName, null, taskIdentityParameters, false /* fuzzy match */, _targetLoggingContext, _taskLocation);

                    if (returnClass == null)
                    {
                        returnClass = _projectInstance.TaskRegistry.GetRegisteredTask(_taskName, null, null, true /* exact match */, _targetLoggingContext, _taskLocation);

                        if (returnClass == null)
                        {
                            returnClass = _projectInstance.TaskRegistry.GetRegisteredTask(_taskName, null, null, false /* fuzzy match */, _targetLoggingContext, _taskLocation);

                            if (returnClass == null)
                            {
                                _targetLoggingContext.LogError
                                    (
                                        new BuildEventFileInfo(_taskLocation),
                                        "MissingTaskError",
                                        _taskName,
                                        _projectInstance.TaskRegistry.Toolset.ToolsPath
                                    );

                                return null;
                            }
```

It always starts by searching for an _exact_ match, which would be any task that supplies default parameters. In my test case, I have a `Foo` task that takes no params. So MSBuild finds `Foo` as an exact match with no parameters before it could find `Foo` with a fuzzy match.

I've tested a quick fix in [the draft PR](https://github.com/dotnet/msbuild/pull/6783) that allows finding the first-defined task even if there was an exact match that would have been found. I saw that it returns the first-defined usingtask, but only when not searching by exact match first. The problem is changing that first search condition _not_ to look for exact matches immediately and the impact it could have on every build.

**Comment by tristanmcpherson** [comment]
I seem to be running into this exact issue, importing Microsoft.VsSDK.targets in VS2022 complains about VSCT not being able to load due to an incorrect format, and specifying a UsingTask doesn't seem to allow me to override this behavior.

**Comment by rainersigwald** [comment]
@tristanmcpherson how are you importing it, exactly? Recent versions of the VSSDK should be ok.

**Comment by tristanmcpherson** [comment]
> @tristanmcpherson how are you importing it, exactly? Recent versions of the VSSDK should be ok.

You're right, it was version 15 that was having issues. Migrated to 17 and everything is working. Thank you for the pointer!
