### ISSUE TITLE
Don't expand list comparisons against empty strings in logging

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/msbuild#5614]
Context: https://github.com/dotnet/roslyn/pull/46445

AFAIK, we special case evaluation of conditions such as `'@(ReferencePathWithRefAssemblies)' == ''` to avoid expanding the item list.  However, if we are logging with a verbose enough level (or binlogging, probably), then we will end up expanding the item list anyway.  To avoid this, projects can use the following instead: `'@(ReferencePathWithRefAssemblies->Count())' == '0'`

If possible, we should consider special-casing the log message in cases like this to also avoid expanding the item list.

**Comment by marcpopMSFT** [comment]
@ladipro thoughts on whether this is a perf fix worth looking into?  Can we improve perf outside of the logging scenario?

**Comment by JaynieBai** [comment]
The related code should be https://github.com/dotnet/msbuild/blob/58c672337b92d9c9975a70ac445a3a4330fa2940/src/Build/BackEnd/Components/RequestBuilder/TargetEntry.cs#L369-L391

**Comment by JaynieBai** [comment]
@AR-May  Since the fix https://github.com/dotnet/msbuild/pull/5553.  The expanding the item list string has been truncated. So I think this issue should have been fixed.  For perfomance，if add one condition for expanded, there should be other parse string analysis  in the left or right  nodes for Condition expression.

**Comment by AR-May** [comment]
I think it is fixed as well.
