### ISSUE TITLE
SDK-style project targeting net471 winform resource has subfolder name in key: MissingManifestResourceException

### ISSUE THREAD

**Issue by msneijders** [dotnet/msbuild#5793]
### Issue Description
My scenario is this:
I have a large line-of-business winforms application, which I am migrating to dotnet5.0. During this migrating period I want to build a net5.0 version and a net471 version -- I dont want to all my customers to migrate all at once.

For this I want to build a net471 winforms application using a sdk-style project (so I can easily use multiple TargetFrameworks). 

My project successfully builds, but fails in runtime. The cause is a Form in a subfolder, which name is not part of its namespace. The generated key for the Form1.resources has the subfolder name in it, but the runtime resourcemanager expects something else.

### Steps to Reproduce
[WindowsFormsApp2.zip](https://github.com/dotnet/msbuild/files/5365612/WindowsFormsApp2.zip)
- Open the added solution.
- Set framework target to net471.
- Run. You get a "System.Resources.MissingManifestResourceException".
- Set framework target to netcore3.1.
- Run. No error.

P.S. opening Form1.resx file in VSStudio using the Managed Resource Editor gives me a NullReference error -- in my actual migrated project file, I can open all resx files, I don't know why this is.

### Expected Behavior
I am expecting to get a runnable winforms application targeting net471 using a sdk-style project file.

### Actual Behavior
I am getting a "System.Resources.MissingManifestResourceException" when targeting net471.

### Analysis
Using Ilspy, I see "WindowsFormsApp2.Subfolder.Form1.resources" in the net471 version. In the netcore3.1 version it says: "WindowsFormsApp2.Form1.resources".

### Versions & Configurations
Microsoft (R) Build Engine version 16.8.0-preview-20452-03+5dee11854 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.8.0.45203

**Comment by msneijders** [comment]
Looks like setting <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention> in the project file makes it work for net471. I took this from https://docs.microsoft.com/en-us/dotnet/core/resources/manifest-file-names -- but it says here "true" is its default value -- am I misreading this?

**Comment by BenVillalobos** [comment]
This is caused by targeting `net472` in an sdk style project, where no `DependentUpon` metadata is set per resource file (like a standard `net472` project would do automatically). See https://github.com/dotnet/docs/issues/16964 for a more explicit description of how these manifest resource names are chosen.

> Looks like setting EmbeddedResourceUseDependentUponConvention to true in the project file makes it work for net471. I took this from https://docs.microsoft.com/en-us/dotnet/core/resources/manifest-file-names -- but it says here "true" is its default value -- am I misreading this?


`EmbeddedResourceUseDependentUponConvention` is in fact set to true for all net core apps >= `3.0`, or all netstandard apps >= `2.1`. Here's the snippet of code that defines this in `Microsoft.NET.Sdk.targets`:
```xml
  <PropertyGroup>
    <EmbeddedResourceUseDependentUponConvention
      Condition="'$(EmbeddedResourceUseDependentUponConvention)' == '' and
                 (('$(TargetFrameworkIdentifier)' == '.NETCoreApp' and '$(_TargetFrameworkVersionWithoutV)' >= '3.0') or
                  ('$(TargetFrameworkIdentifier)' == '.NETStandard' and '$(_TargetFrameworkVersionWithoutV)' >= '2.1'))">true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
```

It looks like targeting `net472` from an sdk style project doesn't opt you into the convention, so manually adding it is the right fix here.

**Comment by Nirmal4G** [comment]
@BenVillalobos The above snippet in the sdk targets should include `.NETFramework` too. Asking us to include is not fair. We should not break expected behavior. People are still using the .NET Framework on Windows, you know!?

**Comment by BenVillalobos** [comment]
@Nirmal4G By default, framework winforms apps generate a `<DependentUpon>` metadata that handles this. So the expected behavior is it uses that data to generate resource names vs automatically inferring it based off of folder structure/namespace. I don't think we considered checking if it were an sdk style project that targeted net472 or net471, or if we can even perform that check (surely there's a property that tells us if a project is sdk style).

Perhaps we could add another check like: `if sdk style project & netframework: set EmbeddedResourceUseDependentUponConvention`? This is all from memory so I may be off base here.

**Comment by Nirmal4G** [comment]
@BenVillalobos

Yes, there's a property called `UsingMicrosoftNETSdk` tells us if we're using the .NET SDK targets. But that's not needed, since the above logic is in SDK targets which means it's only available if we use the Sdk-style project file. Updating the above logic to the following is more than enough.

```xml
​  <​PropertyGroup​ Condition​=​"​'$(EmbeddedResourceUseDependentUponConvention)' == ''">
    <EmbeddedResourceUseDependentUponConvention​ Condition​=​"'$(TargetFrameworkIdentifier)' == '.NETFramework' and '$(_TargetFrameworkVersionWithoutV)' >= '2.0'">true</​EmbeddedResourceUseDependentUponConvention​>
    <EmbeddedResourceUseDependentUponConvention​ Condition​=​"'$(TargetFrameworkIdentifier)' == '.NETStandard' and '$(_TargetFrameworkVersionWithoutV)' >= '2.1'"​>true</​EmbeddedResourceUseDependentUponConvention​>
    <EmbeddedResourceUseDependentUponConvention​ Condition​=​"'$(TargetFrameworkIdentifier)' == '.NETCoreApp' and '$(_TargetFrameworkVersionWithoutV)' >= '3.0'">true</​EmbeddedResourceUseDependentUponConvention​>
  </​PropertyGroup​>
```

I don't know why you're limiting the version of the target framework but isn't this depend on the project system and it's relevant targets? If not, then you could simplify to...

```xml
​  <​PropertyGroup​ Condition​=​"​'$(EmbeddedResourceUseDependentUponConvention)' == ''">
    <EmbeddedResourceUseDependentUponConvention​ Condition​=​"'$(TargetFrameworkIdentifier)' == '.NETFramework'">true</​EmbeddedResourceUseDependentUponConvention​>
    <EmbeddedResourceUseDependentUponConvention​ Condition​=​"'$(TargetFrameworkIdentifier)' == '.NETStandard'"​>true</​EmbeddedResourceUseDependentUponConvention​>
    <EmbeddedResourceUseDependentUponConvention​ Condition​=​"'$(TargetFrameworkIdentifier)' == '.NETCoreApp'">true</​EmbeddedResourceUseDependentUponConvention​>
  </​PropertyGroup​>
```
