### ISSUE TITLE
GenerateBindingRedirects target isn't skipped due to SuggestedBindingRedirects items not being files

### ISSUE THREAD

**Issue by dfederm** [dotnet/msbuild#5943]
### Issue Description
When doing an incremental build (or when one project triggers this target from its dependency), the `GenerateBindingRedirects` target is not skipped as expected in some cases. Specifically this is because `@(SuggestedBindingRedirects)` is listed as an input but does not contain file paths.

### Steps to Reproduce
Add this item (which RAR could plausibly add):
```xml
<SuggestedBindingRedirects Include="Newtonsoft.Json, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed">
  <MaxVersion>12.0.0.0</MaxVersion>
</SuggestedBindingRedirects>
```

Build and build again. The 2nd build won't skip this target when in theory it should. You should see the following in the logs before the target executes.

```
Input file "Newtonsoft.Json, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" does not exist.
```

Attaching image to show the behavior when a project triggers RAR on its dependencies (the error in my case is because our environment doesn't allow projects to write over their dependencies' outputs):
![image](https://user-images.githubusercontent.com/6445614/101391826-bf808000-3879-11eb-8614-8ba7748a3382.png)

### Expected Behavior
The `GenerateBindingRedirects` is skipped

### Actual Behavior
The `GenerateBindingRedirects` executes.

### Analysis
The target is defined as:
```xml
  <Target Name="GenerateBindingRedirects"
    Inputs="$(MSBuildAllProjects);@(AppConfigFile);$(ResolveAssemblyReferencesStateFile);$(IntermediateOutputPath);@(SuggestedBindingRedirects)"
    Outputs="$(_GenerateBindingRedirectsIntermediateAppConfig)"
    Condition="'$(AutoGenerateBindingRedirects)' == 'true' and '$(GenerateBindingRedirectsOutputType)' == 'true'">
```

Potentially `@(SuggestedBindingRedirects)` can smply be removed from the input list. For generated `SuggestedBindingRedirects` items (from RAR), I would think that the RAR state file would have changed (although I'm not 100% confident about that). If a manually added item changes, `MSBuildAllProjects` would certainly change as well.

**Comment by rainersigwald** [comment]
Introduced in http://vstfdevdiv:8080/DevDiv2/DevDiv/_versionControl/changeset/921202, the original GenerateBindingRedirects commit. I think it's just a bug and not a broken remnant of something intentional.

**Comment by yuehuang010** [comment]
+1

**Comment by Forgind** [comment]
> Potentially @(SuggestedBindingRedirects) can smply be removed from the input list. For generated SuggestedBindingRedirects items (from RAR), I would think that the RAR state file would have changed (although I'm not 100% confident about that).

I don't think this is guaranteed to be true. If you run RAR 100 times in a single process within a short time, and all relevant file state information is in the process-level cache, RAR also completely emptied the on-disk cache. (I'm not convinced it _should_ do that, but it does.) At that point, it doesn't matter if you build a completely unrelated project that happens to have an empty RAR state file; the state file won't change—but the suggested redirects can. It may seem a little far-fetched, but it definitely isn't if we bring in RARaaS.

One alternative to just removing it that I considered for this issue is if we had RAR write suggested redirects to a file. Then we could pass the file, making the target UTD check happy, and read it in GenerateBindingRedirects. What do you think?

**Comment by BenVillalobos** [comment]
Does `@(SuggestedBindingRedirects)` _ever_ contain a file that exists on disk?

**Comment by Forgind** [comment]
Not as far as I know. Otherwise, this wouldn't be an issue.
