### ISSUE TITLE
MSBuild doesn’t return outputs from up-to-date targets

### ISSUE THREAD

**Issue by wjk** [dotnet/msbuild#5979]
### Issue Description

I have a C++/WinRT project and a CsWinRT projection project that references it. Since MSBuild does not do so automatically, I wrote some targets to retrieve the *.winmd file paths from the C++ project (stored as a `<ProjectReference>` in the projection project) and put them into the appropriate CsWinRT item type. However, the referenced project is up-to-date (as these tasks are run after project references are built), the target called is skipped and returns no outputs. Therefore, the CsWinRT input item type is not filled and the build fails because there needs to be at least one file here.

### Steps to Reproduce

Zipped solution: [repro.zip](https://github.com/dotnet/msbuild/files/5718714/repro.zip)  
Zipped binlog: [msbuild.zip](https://github.com/dotnet/msbuild/files/5718715/msbuild.zip)  
Command line: `MSBuild /p:Configuration=Debug /p:Platform=x64`

### Expected Behavior

The WinMD files should be returned to the Projection project as items, and CsWinRT would then process them.

### Actual Behavior

The `GetResolvedWinMD` target is not run, and returns no winmd files to the Projection project to process.

**Comment by wjk** [comment]
I have since found out that the true cause of the bug I am writing about here was something completely unrelated to MSBuild. I am going to leave this issue open, however, because I am interested in knowing how MSBuild handles targets with outputs that are called multiple times but only run once. Thanks!

**Comment by Forgind** [comment]
[Documentation](https://docs.microsoft.com/visualstudio/msbuild/incremental-builds?view=vs-2019)

This is an incremental build scenario, so each time it encounters the Target, it checks whether the outputs are already newer than the inputs. If they are (as would be true after the first case, assuming the inputs don't change), it assumes it doesn't need to change the outputs anymore. Since Targets don't really have return anything other than whether they succeeded, you still have access to the outputs and can use them as if the Target had run. Does that answer your question?

**Comment by wjk** [comment]
@Forgind Yes it does. Thank you very much.
