### ISSUE TITLE
[Loc] Assistance with placeholders

### ISSUE THREAD

**Issue by crsuzukimsft** [dotnet/msbuild#6050]
. | .
-- | --
String Resource ID | 0; "CircularDependencyInTargetGraph"
Source String | MSB4006: There is a circular dependency in the target dependency graph involving target "{0}". Since "{1}" has "{2}" dependence on "{3}", the circular is "{4}".
Filename | Build\Resources\xlf\Strings.xlf
Question | Please specify the meaning of the placeholders.

**Comment by crsuzukimsft** [comment]
vcq 352017

**Comment by Forgind** [comment]
0 is the name of a target; 1 is the name of that target's parent (the target that caused it to be executed); 2 is the way in which that dependency was formed, like that it was specified as an AfterTarget or DependsOnTarget; 3 is the same as 0 (and probably should just be 0 again, to be honest); and 4 is a list of the targets that caused the circular dependency, so if A depended on B, which depended on C, which depended on A, it would be like A <- B <- C <- A.

Also, since I'm seeing this now, it might be good to reword this slightly:
MSB4006: There is a circular dependency in the target dependency graph involving target "{0}". "{0}" was executed because "{1}" depended on it via "{2}". The complete circle of dependencies is "{4}".

**Comment by Forgind** [comment]
@haiyuzhu for awareness.

**Comment by haiyuzhu** [comment]
> 0 is the name of a target; 1 is the name of that target's parent (the target that caused it to be executed); 2 is the way in which that dependency was formed, like that it was specified as an AfterTarget or DependsOnTarget; 3 is the same as 0 (and probably should just be 0 again, to be honest); and 4 is a list of the targets that caused the circular dependency, so if A depended on B, which depended on C, which depended on A, it would be like A <- B <- C <- A.
> 
> Also, since I'm seeing this now, it might be good to reword this slightly:
> MSB4006: There is a circular dependency in the target dependency graph involving target "{0}". "{0}" was executed because "{1}" depended on it via "{2}". The complete circle of dependencies is "{4}".

Thanks. The error message looks more native. I can update it to make it better.

**Comment by crsuzukimsft** [comment]
Thank you.
