### ISSUE TITLE
Bizarre failure to expand some variables in PathMap

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/msbuild#6125]
### Issue Description

Most documented predefined variables don't expand inside <PathMap>. No obvious workaround.

### Steps to Reproduce

Add block to project file
````
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Deterministic>true</Deterministic>
    <PathMap>$(ProjectPath)=F:\$(ProjectName)</PathMap>
  </PropertyGroup>
````

run `dotnet build -c Release 2>&1 -v diag | find "PathMap"`

A reproduction is attached [dbuild.zip](https://github.com/dotnet/msbuild/files/5928116/dbuild.zip)

### Expected Behavior

`$(ProjectPath)` expands

### Actual Behavior

`$(ProjectPath)` expands to an empty string

### Analysis

The following variables were tried and do not expand:
$(ProjectName)
$(ProjectDir)
$(ProjectPath)

But $(Configuration) expands so it's not completely failing to detect variables here. Adding quotes around $(ProjectPath) does not help, and wouldn't work if it did expand because `PathMap` does not take quotes.

Existence of $(ProjectDir) taken from here: https://docs.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=msvc-160

### Versions & Configurations

dotnet --version: 5.0.102

**Comment by Forgind** [comment]
I think this is actually expected behavior.

MSBuild guarantees that they will exist, but their values are only set in Microsoft.Common.CurrentVersion.targets. This is imported at the end of the evaluation pass of a project file. This means that a user can set a custom value for those variables, and it won't be overridden, but if they don't set a value, a default value will be given to them at the end of the evaluation pass.

For your example, you tried to use them before Microsoft.Common.CurrentVersion.targets had come in, so they didn't have a value yet. If you want to use them to set a property, you can do that inside a Target. Targets are executed after the project is fully evaluated, so that will let you use their values. Does that make sense?

If I misinterpreted your scenario, let me know, and I can reopen this.

**Comment by jhudsoncedaron** [comment]
If you try to use a Target here I think you will understand that makes no sense. This particular property in propertygroup really needs access to the variables that are being set much later.

**Comment by Forgind** [comment]
I'm sorry, I don't understand what you mean. You can set properties in targets, so if you want to use the default values, why can't you put this in a Target and just make sure it runs before others?

**Comment by jhudsoncedaron** [comment]
I must be missing something.
