### ISSUE TITLE
Reduce List<ProjectRootElement> allocations in Evaluator.cs

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6307]
Evaluator.cs is too liberal allocating `List<ProjectRootElement>` unnecessarily

**Comment by MichalPavlik** [comment]
1) There are places where is the List allocated just to represent empty result. Most straightforward solution would be to use IEnumerable and assign `Enumerable<ProjectRootElement>.Empty` singleton for empty result.

2) We could avoid more allocations with one collection per `EvaluateImportElement` invocation. This instance would be then passed to downstream methods for population. It's a bigger change than (1) because `ExpandAndLoadImports` is adding items to collection conditionally based on result of `ExpandAndLoadImportsFromUnescapedImportExpression`.

3) I was wondering how big is the `importedProjectRootElements` collection in `EvaluateImportElement`, so I did some measurements while building OrchadCore. `EvaluateImportElement` was invoked 26595x and the distribution is:

0 items - 9975
1 item - 16151
2 items -157
5 items -156
8 items 156

The majority here is 0 or 1 item. For these cases, we don't need to allocate a collection at all. We can create specialized collection, which can hold one item in a field and create underlying list only if needed. This would save allocations for size 0 and 1, but it has greater cost for larger sets. It's a speculative optimizations and we would need to gather measurements from more scenarios.

**Comment by drewnoakes** [comment]
For materialised collections consider `ImmutableArray<T>` over `IEnumerable<T>`.

- It is backed by arrays, so very compact
- It has efficient index based lookup
- It has zero-allocation enumeration
- It already defines a singleton empty value
- It is a semi-standard collection

**Comment by MichalPavlik** [comment]
Thanks Drew, that's a valid point and it worth to use `ImmutableArray<T>`.
`List<T>` is also baked by array, but I guess your point is that `List<T>` has one more allocation.
IIRC `List<T>` should also have zero allocation enumeration, because `GetEnumerator()` returns value type based enumerator (unless the explicit interface implementation is called).

**Comment by drewnoakes** [comment]
Another difference between `List<>` and `ImmutableArray<>` is that lists commonly have empty items at the end of their array (size vs. capacity).

Yes `List<>` gives allocation-free enumeration, but only if the declared type is `List<>`. As soon as you cast it to `IEnumerable<>` as you suggest, you will see allocations during enumeration. Having mutable types on public APIs should be avoided where possible. Using `ImmutableArray<>` on APIs is, in my opinion, a nice option for these reasons.
