### ISSUE TITLE
Improve Diagnosability of SDK Resolve Failure

### ISSUE THREAD

**Issue by msfcolombo** [dotnet/msbuild#6391]
When running `msbuild`, `dotnet build` or `dotnet msbuild` in the project below, I get the error:

    C:\repo-path\sample\dirs.proj : error MSB4236: The SDK 'Microsoft.Build.Traversal' specified could not be found.

Here's the project:

```
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" Sdk="Microsoft.Build.Traversal">
  <ItemGroup>
     <ProjectFile Include="Sample\Sample.csproj" />
     <ProjectFile Include="SampleTest\SampleTest.csproj" />
  </ItemGroup>
</Project>
```

When running with `-v diag`, I've noticed that it does not attempt to install or restore the SDK.

I don't know how to install that SDK manually either. Documentation at [https://github.com/microsoft/MSBuildSdks](https://github.com/microsoft/MSBuildSdks) and [https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk) doesn't explain how to install. They just say that restore is automatic.

I also attempted `-target:Restore` but it says ` Target "Restore" skipped. The target does not exist in the project and SkipNonexistentTargets is set to true.`

## msbuild version

```
C:\repo-path\sample>"c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" --version
Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.9.0.16703
```

## dotnet installed SDKs

```
C:\repo-path\sample>dotnet --list-sdks
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.523 [C:\Program Files\dotnet\sdk]
2.1.815 [C:\Program Files\dotnet\sdk]
2.2.110 [C:\Program Files\dotnet\sdk]
2.2.300 [C:\Program Files\dotnet\sdk]
3.0.103 [C:\Program Files\dotnet\sdk]
3.1.114 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
```

The problem happens when I select SDK `3.1.114` or `5.0.202`. I confirm that in both cases it's searching the msbuild SDK on directory `C:\Program Files\dotnet\sdk\{dotnet-SDK-version}\Sdks\Microsoft.Build.Traversal\Sdk`, and it's not finding there because it does not exist.

I don't know how to install the msbuild SDK manually or what to do to fix the environment.

**Comment by msfcolombo** [comment]
I found the issue. Missing `global.json` file. Please improve the error message, or add more stuff to diagnostics verbosity. It tells absolutely nothing about search for `global.json`.

Thanks!

**Comment by jeffkl** [comment]
This will be improved due to https://github.com/dotnet/msbuild/pull/6312 which will fail the build at least

This documentation explains how to use MSBuild project SDKs: https://github.com/Microsoft/MSBuildSdks#how-can-i-use-these-sdks

This does as well: https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019#how-project-sdks-are-resolved

> A NuGet-based resolver that queries your configured package feeds for NuGet packages that match the ID and version of the SDK you specified.
>
>  This resolver is only active if you specified an optional version. It can be used for any custom project SDK.

Its really hard to know that the reason that an SDK couldn't be resolved was because a version wasn't specified because each SDK resolver may or may not need a version.

**Comment by msfcolombo** [comment]
Besides that, logs should tell that it attempted to open `global.json` to resolve the version, and could not find the file.

**Comment by rainersigwald** [comment]
I feel like an aspect of the original design of SDK resolvers was lost here: each resolver can fail to find an SDK, and that's fine because there's a chain of them and the next one might. But if none of them do, we should emit the errors from each resolver, which would help pinpoint this.

I thought we had a preexisting bug for this but I can't find it now, so this is it.

**Comment by msfcolombo** [comment]
Possibly related: https://github.com/dotnet/sdk/issues/18048.
