### ISSUE TITLE
Veracode Scan Show "Very High" Severity Security Threat within MSBuild Library 

### ISSUE THREAD

**Issue by harexelizaga** [dotnet/msbuild#6396]
Hi,

The company I work for utilizes MSBuild and we appreciate the work you guys have done. Thank you! We use Veracode to detect if any security threats exist within our code. After running a scan, Veracode detected a "very high flaw" within the MSBuild library. I've attached a screenshot of the flaw and its location. The error is, "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')." 
[Here is a link to an in depth explanation of this weakness.  ](https://cwe.mitre.org/data/definitions/78.html)

![image](https://user-images.githubusercontent.com/83475882/116755789-a7370c00-a9a6-11eb-8048-398cdb2d3122.png)
![image](https://user-images.githubusercontent.com/83475882/116755913-e5ccc680-a9a6-11eb-9131-b7a4ffc9bfa2.png)
![image](https://user-images.githubusercontent.com/83475882/116755991-0d239380-a9a7-11eb-8b3a-034058d54cc6.png)

Here are some solutions we've tried:

- Updated the version of the package to the most recent one. It still gave out the error.
- Tried to downgrade the version of the package to see if that would make a difference. It still gave out the error. 

If you have any suggestions and/or concerns please do not hesitate to contact me! We can work together to solve this weakness within the MSBuild library! Looking forward to hearing from you guys! Have a wonderful day! :)

**Comment by blowdart** [comment]
Hi @harexelizaga. I reached out to Veracode because we were puzzled, none of those functions take user input in any way, and so don't need filtering for unescaped paths or any other type of oddness that could cause vulnerabilities. 

TLDR: You're safe, these aren't strictly false positives, but an artifact of how you're using the tool which needs adjusting.

When you upload an application for analysis to Veracode you have to also upload its dependencies. By default, they scan the top-level module -- the first party .EXE(s) or .DLL(s) containing known entry points, e.g. Page_Load(), etc. That way they only scan your actual code plus dependency code including the context in which those dependencies are used (and build tasks aren't dependencies, you don't deploy those with your application).

However, you can override that default and choose to scan everything as a top-level module. In this case, you've likely elected to treat `microsoft.build.utilities.core.dll` (and others) as a standalone application.  Since there are no real entry points, the exported functions as entry points and any values passed into those functions as tainted. This is a design choice Veracode made because they figure if you're scanning a library, you want to assume the worst about how people are using it.

The OS command injection flaws you have resulted from them `microsoft.build.utilities.core.dll` as a standalone application. Veracode's guidance around module selection is: "For the most optimal, relevant and actionable findings we recommend only selecting first party modules without an entry point or with an entry point that is user facing." 

More context: https://community.veracode.com/s/article/What-are-Modules-and-how-do-my-results-change-based-on-what-I-select

**Comment by BenVillalobos** [comment]
close?
