### ISSUE TITLE
Bot to automatically comment on issues and apply labels as appropriate

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#6472]
It would be nice to have a bot to automatically manage issues. Proposed design:
1) If an issue has seen no action for 60 or more days, send message "Is this issue still relevant? If so, please comment here. Thank you!" Then add needs:Author Feedback label.
2) Once per week (or more often), look at all needs:Author Feedback-labelled issues.
a) If an issue has not been responded to by anyone, and the label was applied at least 3 weeks ago, close it.
b) If an issue has been responded to by a non-MSBuild maintainer but not an MSBuild maintainer, remove the needs:Author Feedback label and apply untriaged.
c) If an issue has been responded to by both, remove the needs:Author Feedback label but do not apply untriaged.

Sound reasonable?

**Comment by marcpopMSFT** [comment]
CC @maryamariyan who has experience with the labeler that the runtime uses. Maryam, can we enable the labeler in SDK repo to label issues now as I think there are enough items with each label to try that out? Does the labeler work for the scenario described above of trying to shut down older tickets or is it just for labeling? Would there be a different bot that other team's use?

**Comment by rainersigwald** [comment]
Fabric-bot, which we already use, can do these things. I'm not a fan of the former, but a bot to keep our requested-more-info/got-a-reply stuff up to date would be nice.

**Comment by japj** [comment]
I understand wanting to close stale issues.

However as an outsider, having submitted issues to various different github repositories: it is really disheartening when issues submitted go unnoticed and/or are not responded by developers to just get closed automatically even though the problem is still actual (and having spend a fair bit of work getting information together for reporting)

I have responded to several “about to close” notices in other repositories, just to have nothing with it being done.

So my experience is a bit colored (and I totally understand it from your side too), but I just wished there was a better solution to address the core issue that is trying to be solved with auto closing issues.

**Comment by rainersigwald** [comment]
> it is really disheartening when issues submitted go unnoticed and/or are not responded by developers to just get closed automatically even though the problem is still actual (and having spend a fair bit of work getting information together for reporting)

I agree 100% here. Just because an issue is old, doesn't mean it's not real.

However, I think there's room to improve the case where we request specific additional information because we don't understand the bug or can't repro it and don't get that information. I'm making a bunch of comments to that effect on #6474.

**Comment by marcpopMSFT** [comment]
I definitely appreciate the feedback here. From my perspective, part of this is trying to figure out the priority of incoming issues. A lot of issues filed in the MSBuild repo in particular are of the nature of a specific customer build failed.  Those are hard for us to know how to prioritize as we don't want to miss any issue that could be affecting a larger segment of our customers while recognizing that we won't be able to help solve every customer issue. I think it's a delicate balance and we have to be very careful and deliberate with how we use such a bot.

**Comment by BenVillalobos** [comment]
> I think it's a delicate balance and we have to be very careful and deliberate with how we use such a bot.

@marcpopMSFT Agreed, which is why the bot will stick to a small subset of issues to begin with (anything after a particular date, with specified labels). We'll update it as we go
