### ISSUE TITLE
Exclude globs that look like **\subdir\** do not exclude files without extensions

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#6502]
### Issue Description

A regression introduced in #6151.
Reported by @ForNeVeR in https://github.com/dotnet/sdk/issues/17976.

### Steps to Reproduce

Use an exclude glob that looks like `**\subdir\**` and have a file without extension under a `subdir` subdirectory.

Example:

```xml
<Project>
  <ItemGroup>
    <Test Include="dir\**" Exclude="**\subdir\**" />
  </ItemGroup>

  <Target Name="Build">
    <Message Text="@(Test, ', ')" />
  </Target>
</Project>
```

With a file structure as follows:

```
│   expand.proj
│
└───dir
    └───subdir
            file1.ext
            file2
```

### Expected Behavior

Does not print anything. All included `Test` items are immediately excluded.

### Actual Behavior

Prints `dir\subdir\file2`.

### Analysis

This is another issue with taking `*.*` too literally. In this case the default filespec is added when parsing `**\subdir\**` which is understood as `**\subdir\**\*.*` and files are matched against the actual `.` dot.

### Versions & Configurations

Introduced in 16.10.

**Comment by ForNeVeR** [comment]
For future visitors, see https://github.com/dotnet/sdk/issues/17976#issuecomment-851586554 for a possible workaround.

**Comment by ahmedalejo** [comment]
@ladipro this issue seems to be back again.
With the following folder structure
```
│   API.csproj
│
└───wwwroot
    └───.well-known
            apple-app-site-association
```
All except the `.well-known` isn´t include when published.
It also shows as hidden in vs explorer as well.
It looks like it is now not being added by default.
![image](https://user-images.githubusercontent.com/7012074/126782357-156446d1-519b-4a73-ae94-adb1fb0959b3.png)

I will try adding back
`<Content Include="wwwroot\.well-known\**" />`
I removed this initially due to the this bug (i.e. #17976)

### MSBUILD
That's exactly what I´m facing. My build fails intermittently on Azure DevOps agent.
- ✔`Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET` publish includes `wwwroot/.well-known` folder
- ❌`Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET` publish **does not** includes `wwwroot/.well-known` folder

**Comment by ladipro** [comment]
@ahmedalejo thank you for reporting this. The new behavior is actually by design and what you're seeing with `16.10.1+2fd48ab73` was a bug. Apologies for the inconvenience. I've left a comment in #6708.
