### ISSUE TITLE
Deleting .pdb leads recompilation in some case in 16.9.6

### ISSUE THREAD

**Issue by sinall** [dotnet/msbuild#6526]
### Issue Description

Deleting .pdb of **static library project** leads recompilation in some case in 16.9.6

### Steps to Reproduce

1. Compile solution successfully
2. Delete .pdb file in Debug/Release folder
3. Press 'Ctrl+Shift+B', it recompiles al cpp files again

### Expected Behavior

It should re-link again without compiling.

### Actual Behavior

It re-compiles all cpp files including stdafx.cpp, etc.

### Versions & Configurations

16.9.0.16703

### Attach a binlog

I cannot use 16.10 at this moment, do you know which previous version don't have this issue?

**Comment by AraHaan** [comment]
I belive that this issue is more or so about either cl.exe or the Visual Studio version of MSBuild https://github.com/microsoft/msbuild/

**Comment by AraHaan** [comment]
For that you might want to look into enabling incremental builds then (generates an ipdb file) which I think is used to check if the files need rebuilt. However I think what the compiler *should* do is calculate a checksum of the file after it's written and then write to a file of the same name but adds an ``.sha`` extension and is an sha512 checksum of the file (or whatever version of sha is the latest and has a super low collision rate).

**Comment by sinall** [comment]
> For that you might want to look into enabling incremental builds then (generates an ipdb file) which I think is used to check if the files need rebuilt. However I think what the compiler _should_ do is calculate a checksum of the file after it's written and then write to a file of the same name but adds an `.sha` extension and is an sha512 checksum of the file (or whatever version of sha is the latest and has a super low collision rate).

The solution has several projects, currently the issue happens in the static library projects.

**Comment by rainersigwald** [comment]
> I belive that this issue is more or so about either cl.exe or the Visual Studio version of MSBuild https://github.com/microsoft/msbuild/
> 
> Edit: odd looks like their msbuild relocated to here.

This is the right repo for issues with MSBuild whether they're in `dotnet build`, `msbuild.exe`, or Visual Studio scenarios. It was moved from `microsoft/msbuild` to make some of the .NET release process stuff easier.

Team triage: However, this issue is about incremental build in C++ scenarios, and the code for that is not in this repo (it's in the internal Visual Studio codebase). Can you please [open a feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)? Please post the link here and we can help expedite routing.
