### ISSUE TITLE
The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located

### ISSUE THREAD

**Issue by nssidhu** [dotnet/msbuild#6604]
I am trying to open existing Blazor wasm hosted project with .net 6.
But i run into the following Error.

error  : The project file cannot be opened. The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not find file 'C:\Program Files\dotnet\sdk-manifests\6.0.100\Microsoft.NET.Workload.Android\WorkloadManifest.json'.

**Comment by kucint** [comment]
I have similar issue when trying to install maui check global tool:

C:\WINDOWS\system32>dotnet tool install --global redth.net.maui.check
C:\Users\tk\AppData\Local\Temp\nh0zgckh.lfk\restore.csproj(5,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not find file 'C:\Program Files\dotnet\sdk-manifests\6.0.100\Microsoft.NET.Workload.Android\WorkloadManifest.json'.
C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not find file 'C:\Program Files\dotnet\sdk-manifests\6.0.100\Microsoft.NET.Workload.Android\WorkloadManifest.json'.
C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found. [C:\Users\tk\AppData\Local\Temp\nh0zgckh.lfk\restore.csproj]
The tool package could not be restored.
Tool 'redth.net.maui.check' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by rainersigwald** [comment]
There are some workarounds for this issue at https://developercommunity.visualstudio.com/t/ASPNET-Core-project-does-not-load-in-Vi/1453652

**Comment by BenVillalobos** [comment]
Team Triage: The error can be handled better on our part, see #6594. Please follow the workaround in the developer community issue linked above

**Comment by kucint** [comment]
> 
> 
> There are some workarounds for this issue at https://developercommunity.visualstudio.com/t/ASPNET-Core-project-does-not-load-in-Vi/1453652

thanks, it worked for me.
