### ISSUE TITLE
Floating version for a custom SDK

### ISSUE THREAD

**Issue by apisarev** [dotnet/msbuild#6697]
Why NuGet-based SDK resolver requires exact version number:
```XML
<Project Sdk="My.Awesome.Sdk/1.0.3">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
```
 
And you can't specify a floating version (e.g. 1.0.*) available for NuGet Package Reference
[https://docs.microsoft.com/en-us/nuget/concepts/package-versioning](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning)

**Comment by jeffkl** [comment]
MSBuild project SDKs fetched from NuGet are considered expensive.  This is because the APIs must query a URI and potentially download a package.  This operation must happen before a project is loaded so it has an impact on build times and can make Visual Studio slow for the first load of a project.  NuGet has a file-based caching mechanism so if a package is already on disk it does not need to query the network.  The NuGet-based MSBuild project SDK resolver heavily relies on this caching mechanism to ensure that project loading is fast as a package is only ever fetched once per version.  If you were able to use a floating version then NuGet would need to query the feed for every project load.  There is an HTTP cache but it only lasts an hour or two.  

So the NuGet-based MSBuild project SDK resolver will never support floating versions.  Systems are available now that update package versions for you in an automated way (like [dependabot](https://dependabot.com/)) so I would recommend that anyway.  Floating versions introduce non-deterministic behavior for the sake of convenience.  Automated version updates via the normal Pull Request process is much more precise without sacrificing determinism.
