### ISSUE TITLE
Suppress NU1701 warning?

### ISSUE THREAD

**Issue by elachlan** [dotnet/msbuild#7212]
Should NU1701 be suppressed, is there another fix, or should it be left alone?
```
Warning	NU1701	Package 'xunit.runner.visualstudio 2.4.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	Xunit.NetCore.Extensions msbuild\src\Xunit.NetCore.Extensions\Xunit.NetCore.Extensions.csproj	1
```

**Comment by Forgind** [comment]
Team triage: We don't think this should be suppressed because we think it might be a sign of an underlying bug (maybe in NuGet?). Worth investigating at some point but not our top priority.

**Comment by rainersigwald** [comment]
Ah I see what's up here. That project references `Xunit.Core` (because it needs xunit types), which defines `IsTestProject=true`. Then Arcade's `tests.targets` checks that and imports `XUnit.targets`

https://github.com/dotnet/arcade/blob/98018d5a808e5167a4ce5e81dc6513382676d4c9/src/Microsoft.DotNet.Arcade.Sdk/tools/Tests.targets#L83

which adds a reference to xunit.runner.visualstudio

https://github.com/dotnet/arcade/blob/98018d5a808e5167a4ce5e81dc6513382676d4c9/src/Microsoft.DotNet.Arcade.Sdk/tools/XUnit/XUnit.targets#L10

even though that's not really needed.

**Comment by rainersigwald** [comment]
So I _think_ we can add

```xml
<IsTestProject>false</IsTestProject>
```

in `Xunit.NetCore.Extensions.csproj` and solve this. However, I haven't been able to repro the problem to verify. I have seen it many times before while doing other things . . . but now that I'm trying to see it I can't.

Anybody have repro steps handy?

**Comment by Forgind** [comment]
I just open MSBuild.Dev.slnf on main and build in VS 2022, and it pops up in the error list.

For me, at least, adding that line did indeed make the problem go away without breaking anything else 🙂 I'll make a PR and credit you.
