### ISSUE TITLE
Add a runtime check for Microsoft.IO.Redist

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/msbuild#7335]
Since https://github.com/dotnet/msbuild/pull/6771 merged, the net472 build uses Microsoft.IO.Redist (M.IO.R) instead of System.IO. This is a problem when running the net472 build on Linux or MacOS, since M.IO.R pinvokes into Kernel32 which is a Windows library.

```
1093 System.EntryPointNotFoundException: GetFullPathNameW assembly:<unknown assembly> type:<unknown type> member:(null) 
1094 at (wrapper managed-to-native) Interop+Kernel32.GetFullPathNameW(char&,uint,char&,intptr) 
1095 at System.IO.PathHelper.GetFullPathName (System.ReadOnlySpan`1[T] path, System.Text.ValueStringBuilder& builder) [0x0001c] in <d528d43e4d354c288aa6a5ce49a5eba7>:0 
1096 at System.IO.PathHelper.Normalize (System.String path) [0x00021] in <d528d43e4d354c288aa6a5ce49a5eba7>:0 
1097 at Microsoft.IO.Path.GetFullPathInternal (System.String path) [0x0000f] in <d528d43e4d354c288aa6a5ce49a5eba7>:0 
1098 at Microsoft.IO.Path.GetFullPath (System.String path) [0x00044] in <d528d43e4d354c288aa6a5ce49a5eba7>:0 
```

It would be good to have a runtime check and fallback to System.IO on non-windows platforms.

**Comment by rainersigwald** [comment]
@AR-May, does this sound like something that you could do?

**Comment by teo-tsirpanis** [comment]
`Microsoft.IO.Redist` has been discontinued (dotnet/runtime#58359). With Visual Studio's imminent move to .NET Core-based MSBuild in #7258, perhaps it's time to discontinue it from MSBuild too. If it's so decided I will try it out.

**Comment by adamsitnik** [comment]
> did I miss some deprecation communication there

You have not, as we haven't made it yet.

We have tried to find users of it (https://github.com/dotnet/runtime/issues/54919#issuecomment-870870457), but we did not find any. Since it was increasing the complexity (#if defs for .NET and .NET Framework) and maintenance (the logic had to be tested for both runtimes) we decided to stop shipping it. It means that we won't be adding new APIs to it, but if you hit a bug in the version that we have shipped with .NET 6, we are (most likely) going to fix it.

cc @jeffhandley
