### ISSUE TITLE
Suggest:  Once = true attribute for Targets to allow target only executed once per solution. in Directory.Build.targets

### ISSUE THREAD

**Issue by softwarekamal** [dotnet/msbuild#7437]
**Shortly,**
1. If you have a Target that executed after build in Directory.Build.targets file.
2. It will executed for each csproj Project
3. Its awesome to do an attribute like `<Target Name = "CleanSolution" Once=true> </Target>`
4. It only executed once. (Whether we build single project or whole solution)

I came back here really when I try to execute a target only once. I try to add a lock file. But It need much deal with stop build, So I try to count the current working project and increase flag file (File that contains numeric value). I increase file in when <Target> called. Then when (flag file number = project counts - 1). the target are called. So it will called once. But actually it didn't work well. During sometimes Build are stop. I need to delete flag file and re-create it again. Too long journey that never worked for me.

I found some people ask about that. But answers suggest using DispatchToInnerBuilds. (Which are not very clear to me....)
From comment found in link 
https://stackoverflow.com/questions/46675782/how-to-make-an-msbuild-target-that-only-runs-once-instead-of-once-before-target

**DispatchToInnerBuilds seems to only work for projects with TargetFrameworks**

So please is there any feature/or maybe you need to implement something like that:

```
	<Target Name="CleanSolution" Once="true" AfterTargets="AfterBuild">
		<Exec Command="del /Q /F &quot;$(OutputPath)*.pdb&quot;,&quot;$(OutputPath)*.xml&quot;"/>
	</Target>
```

Thank you much MSBuild, Visual Studio team. We appreciate your great efforts!

**Comment by jrdodds** [comment]
Hi @softwarekamal,
I think you want to use `$(TargetName)`. But I'll get to that.

MSBuild is project oriented and within a project a target will only run once. Having a `Once` attribute on `Target` doesn't make sense.

When MSBuild is given a .sln file, it create a 'meta project' from the .sln and then runs that generated project. The projects that are members of the .sln are run in separate contexts from the 'meta project'.

You can see the generated meta project by setting the environment variable `MSBUILDEMITSOLUTION` to 1 as documented in [Troubleshooting](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-build-specific-targets-in-solutions-by-using-msbuild-exe?view=vs-2022#troubleshooting).

In a sense what you are actually asking for, is to have a custom target be run as part of the sln meta project.

From the command line you can already do this by creating `before.{solutionname}.sln.targets` and `after.{solutionname}.sln.targets` files as documented in [Customize the solution build](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2022#customize-the-solution-build). Unfortunately when building within Visual Studio, these files are not used.

A better 'ask' than adding a `Once` attribute to `Target`, might be to request that Visual Studio support the before|after.*.sln.targets files so that Visual Studio and command line builds are more consistent.

But all that said, for your example MSBuild code, I would advise:

- If possible, adjust your project settings to prevent creating the unwanted files. The generation of the .pdb and .xml files can be turned off.
- Use `$(OutputPath)$(TargetName).pdb` and `$(OutputPath)$(TargetName).xml`. $(TargetName) is a standard property and is the base name of the primary output file for the current project. By specifying $(TargetName), it is actually okay and desirable to run the target for each csproj project.
- Use the [Delete task](https://docs.microsoft.com/en-us/visualstudio/msbuild/delete-task) instead of an Exec.

Thanks

**Comment by softwarekamal** [comment]
Hello [jrdodds](https://github.com/jrdodds)
Thank you much for your fast reply. I search for solution targets. But actually looks it can't run inside Visual Studio. 

https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2022#customize-the-solution-build

> solution build in this way applies only to command-line builds with MSBuild.exe. It does not apply to builds inside Visual Studio

I give a test but when I rebuild solution. the Solution Target not executed....
![image](https://user-images.githubusercontent.com/33269552/156843999-11e8518b-619b-470c-a8ad-8b6301785c50.png)

**Comment by jrdodds** [comment]
Yes. When I wrote "Unfortunately when building within Visual Studio, these files are not used", that is what I was making reference to.

**Comment by jrdodds** [comment]
Have you tried the following?

```
	<Target Name="CleanSolution" AfterTargets="AfterBuild">
            <Delete Files="$(OutDir)$(TargetName).pdb;$(OutDir)$(TargetName).xml" />
	</Target>
```

**Comment by softwarekamal** [comment]
Hello [jrdodds](https://github.com/jrdodds),
Thank you much for your effort dear

Yes command work. But if you use third-party .dll libraries the *.xml files still generated for these libraries.

If you have 4 projects that references these (3rd parties dlls)
The .xml and .pdb still exists for 3rd parties libraries

Should I use loop or something like <Delete Files="@(DeleteAfterBuild)" />
https://stackoverflow.com/questions/851647/how-to-delete-multiple-files-with-msbuild-web-deployment-project

**Comment by jrdodds** [comment]
Hi @softwarekamal,
MSBuild is declarative and has no loops (like standard SQL). An `ItemGroup` is used to create a set of items which can then be provided to a task like `Delete`.

Are the third party DLLs being referenced as NuGet packages?

Are you using the same output directory (i.e. `$(OutDir)`) for every project in your solution or does each project have its own output directory?

Thanks

**Comment by softwarekamal** [comment]
Hello dear,
Yes I use the same output directory,

I try command your provided `<Delete> ` It worked with combination with this question:
https://stackoverflow.com/questions/851647/how-to-delete-multiple-files-with-msbuild-web-deployment-project

Final result is: (I feel more code to achieve result)
```
	<Target Name="CleanUnusedFilesAfterBuild" AfterTargets="AfterBuild">
		<ItemGroup>
			<FileToDelete Include="$(OutputPath)\*.pdb"/>
			<FileToDelete Include="$(OutputPath)\*.xml"/>
		</ItemGroup>
		<Delete Files="@(FileToDelete)"/>
	</Target>
```

I wonder why short code `<Delete Files = "$(OutputPath)\*.xml"/`> not worked...

**Comment by jrdodds** [comment]
```
	<Target Name="CleanUnusedFilesAfterBuild" AfterTargets="AfterBuild">
		<ItemGroup>
			<FileToDelete Include="$(OutputPath)\*.pdb"/>
			<FileToDelete Include="$(OutputPath)\*.xml"/>
		</ItemGroup>
		<Delete Files="@(FileToDelete)"/>
	</Target>
```

and

```
	<Target Name="CleanUnusedFilesAfterBuild" AfterTargets="AfterBuild">
		<Delete Files="$(OutputPath)\*.pdb;$(OutputPath)\*.xml"/>
	</Target>
```

should be equivalent.

But I would use the first version, even though it is longer. I think the first version is slightly easier to understand and maintain.

**Comment by drewnoakes** [comment]
Deleting outputs during build will lead to your projects being eternally out of date and always being built, which will negatively impact your productivity.

Some ideas to consider:

- Rather than delete XML and PDB files, configure the projects not to produce these in the first place. 

- It seems like you're trying to tidy up the output directory. I'm guessing this is for some kind of publishing or packaging purpose. Could you customise the Publish operation rather than the Build one?

**Comment by jrdodds** [comment]
@softwarekamal, I agree with @drewnoakes.

Also note that the PDB (Program DataBase) files are used by the debugger and removing the .pdb files from Debug builds is probably not a good idea.

**Comment by softwarekamal** [comment]
Hello [drewnoakes](https://github.com/drewnoakes) and [jrdodds](https://github.com/jrdodds)
You both are really helped me enough!
The output path became nightmare. When I try to remove (files generated by compiler). Sometimes I got error message can't copy Foo.xml file messages, 

As you mentioned [drewnoakes](https://github.com/drewnoakes) The projects always being built. plus I got error tons of errors during I try to remove *pdb file with AfterBuild target. while it also produced by other project. Its really fun scenario I try to do.

> Unable to delete file "Build\bin\Debug\CefSharp.Core.Runtime.pdb". The process cannot access the file 'Source\Build\bin\Debug\CefSharp.Core.Runtime.pdb' because it is being used by another process.

So. All I need in Release Configuration I need delete *.xml, *.pdb, etc. And yes I try to publishing without any redundant files.
Yes I can prevent *.pdb files for solution projects only. not 3rd party tools. It must copied, That's why I wish to execute a delete *.pdb after whole solution build. Otherwise sometimes I will got above error in quote ""

Should I create a batch.bat file for that... and just click on it when I need to clean the bin/Release folder from redundant files?

After I build a solution. I got many redundant files and folders. Which I can't prevent them from published. as its shipped with any 3rd party toolkits ex:- nuget, etc. ( I need to remove *.pdb, *.xml, localization folders (en, es, etc) ) and some other extensions that I can't prevent visual studio to generate them. That's why I must find a click-once/or MSBuild Targets that executes once to do that.

Thank you much both.
I still need something to do in .targets file to executes only once per whole solution!

**Comment by amaitland** [comment]
Perhaps you need to consider a different approach, rather than deleting the files, perhaps removing them from the list of files that's copied would be better.

Example might look something like:

```c#
<Target Name="ExcludeFilesAfterResolveAssemblyReferences" AfterTargets="ResolveAssemblyReferences" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <_ReferenceCopyLocalFiltered Include="@(ReferenceCopyLocalPaths)" Condition="'%(Filename)%(Extension)' == 'MyDll.pdb'" />
      <_ReferenceCopyLocalFiltered Include="@(ReferenceCopyLocalPaths)" Condition="'%(Filename)%(Extension)' == 'MyDll.xml'" />
      <ReferenceCopyLocalPaths Remove="@(_ReferenceCopyLocalFiltered)" />
    </ItemGroup>
</Target>
```

You'd have to workout the exact syntax for your scenario. 

Just an idea.

**Comment by Forgind** [comment]
I haven't read all of the above, but here's a neat trick for making a target only build once:
Make a project that does nothing but build the one target. This can be very simple—not even an SDK.
Other projects, rather than building the same target, can build the project with <MSBuild Projects="..."... />. Targets already only build once per build per project per set of global variables, so if you remove any extra global variables, it should make that target build just once per build as desired.

Hope that helps!

**Comment by jrdodds** [comment]
At this point this issue is not a defect or an enhancement to MSBuild. It is a 'how to' question.

**Comment by Forgind** [comment]
True. Moved it to the Discussion milestone.

**Comment by softwarekamal** [comment]
Hello @amaitland,
I tested your code. But nothing worked. I try following to make sure it can delete a specific DLL or something. But the DLL exported after build in Release.

```
	<Target Name="ExcludeFilesAfterResolveAssemblyReferences" AfterTargets="ResolveAssemblyReferences" Condition="'$(Configuration)' == 'Release'">
		<ItemGroup>
			<_ReferenceCopyLocalFiltered Include="@(ReferenceCopyLocalPaths)" Condition="'%(Filename)%(Extension)' == 'CefSharp.BrowserSubprocess.Core.dll'" />
			<_ReferenceCopyLocalFiltered Include="@(ReferenceCopyLocalPaths)" Condition="'%(Filename)%(Extension)' == 'MyDll.xml'" />
			<ReferenceCopyLocalPaths Remove="@(_ReferenceCopyLocalFiltered)" />
		</ItemGroup>
	</Target>
```

Can you help please on that?

**Comment by softwarekamal** [comment]
Hello [Forgind](https://github.com/Forgind),
Please  I don't really understand how to apply that...
If you refer to my [comment ](https://github.com/dotnet/msbuild/issues/7437#issuecomment-1060067517)

> The projects always being built. plus I got error tons of errors during I try to remove *pdb file with AfterBuild target. while it also produced by other project.

Am not 100% understand how ResolveAssemblyReferences target works. And I wish I can, I need to remove specific files and folders that I can't prevent them from generating. That's why I need execute a simple Target only once to remove these files/folders. 

This is the last solution I came with. But I still sometimes when build I got error in Quotes "" above. 

```
	<Target Name="CleanUnusedFilesAfterBuild" Condition="'$(Configuration)' == 'Release'" AfterTargets="AfterBuild">
		<!-- Remove *.xml, *.pdb files -->
		<ItemGroup>
			<FileToDelete Include="$(OutputPath)\*.pdb"/>
			<FileToDelete Include="$(OutputPath)\*.xml"/>
		</ItemGroup>		
		<Delete Files="@(FileToDelete)"/>

		<RemoveDir Directories="$(OutputPath)\ru;$(OutputPath)\de;$(OutputPath)\es;$(OutputPath)\ja"/>
		<RemoveDir Directories="$(OutputPath)\locals"/>
	</Target>
```

Thank you much men, Am waiting for more satisfied workaround.

**Comment by softwarekamal** [comment]
Hello [Forgind](https://github.com/Forgind),
> Make a project that does nothing but build the one target. This can be very simple—not even an SDK.

Also your scenario maybe works in solution build. But sometimes I need build only specific project. 
(So I need a **Shared Target** concept). Which can work in solution build or project build. (Only once).
That's why I think creating empty project to do one target maybe not work in project build level. (I don't sure!)

Am waiting for more explanation for your [idea](https://github.com/dotnet/msbuild/issues/7437#issuecomment-1064343213)! :)

Thank you much men.

**Comment by amaitland** [comment]
> I tested your code. But nothing worked. I try following to make sure it can delete a specific DLL or something. But the DLL exported after build in Release.

@softwarekamal I'd suggest having msbuild create a structure log and using https://msbuildlog.com/#usingbl to debug, you can then look at the different targets and their item groups. Work out exactly what you need for your scenario.

https://github.com/cefsharp/CefSharp/blob/cefsharp/99/NuGet/CefSharp.Common.targets#L10 contains the actual targets I use in CefSharp for different scenarios. 

I don't work for Microsoft, someone here will likely be able to provide better support than I.

**Comment by Forgind** [comment]
It should work without a solution, too. I attached a simple group of 3 projects to illustrate the idea. (`dotnet build temp.csproj` to see it in action)

temp.csproj builds runOnce.proj and middle.proj as well as printing something. middle.proj prints something then builds runOnce.proj. runOnce.proj prints something. Since both temp.csproj and middle.proj build runOnce.proj (and specify to build that target in particular), it should print twice, but because MSBuild only runs a target once per project per set of global properties, it only prints once then skips it.

Note that unless your project is as simple as mine, you'd likely have to make sure you don't accidentally pass global properties to your equivalent of runOnce.proj, but I'm sure you get the idea.

[temp.zip](https://github.com/dotnet/msbuild/files/8235643/temp.zip)

**Comment by softwarekamal** [comment]
Hello @Forgind,
It works perfect!, But please I can't access OutputPath property in runOnce.proj it shown empty in Output window.
_NOTE: I use normal .NET Framework VS build not dotnet build._

I upload what I tried here https://github.com/softwarekamal/tempNewRepo
Please can you look at Directory.Build.targets  why OutputPath not printed in runOnce.proj

Finally, can you please what you mean by:
> but because MSBuild only runs a target once per project per set of global properties, it only prints once then skips it.
Do you mean if we use `<MSBuild>` task in all projects or general Directory.Build.targets file The target only called once? Is this default behavior? or a hack made in example.....

Thank you much dear.

**Comment by softwarekamal** [comment]
Hello @amaitland, Your solution are 99.9% now But ->
I try the ResolveAssemblyReferences target. Its really awesome and works 99%. After I search for that I find follows:

```
<Target Name="RemoveSatelliteAssemblies" AfterTargets="ResolveAssemblyReferences">
		<ItemGroup>
			<!-- get list of assemblies marked as CopyToLocal -->
			<FilesToExclude Include="@(ReferenceCopyLocalPaths)" Condition="'%(Extension)' == '.xml' OR '%(Extension)' == '.pdb'" />
			<ReferenceCopyLocalPaths Remove="@(FilesToExclude)"  />
		</ItemGroup>

		<Message Text="Excluded @(FilesToExclude->'%(Filename)%(Extension)', ', ')" Importance="high"/>
	</Target>
```

Ok this is cool for xml, pdb files? How to exclude custom folders for example \locals, \en, etc.
Please any workaround?

Thank you much dear

**Comment by softwarekamal** [comment]
After long journey. The MSBuild is a nightmare. I deleted 3rd parties library itself. rather than $(OutputPath), and learn from some mistakes.

I finally combine multiple solutions together from
I combine @jrdodds [Solution](https://github.com/dotnet/msbuild/issues/7437#issuecomment-1059619357)
with @amaitland [Solution](https://github.com/dotnet/msbuild/issues/7437#issuecomment-1061267484)

Here's final results

```
	<Target Name="RemoveUnusedReferences" AfterTargets="ResolveAssemblyReferences">
		<ItemGroup>
			<!-- Remove .xml, .pdb and localizations files -->
			<FilesToExclude Include="@(_ReferenceRelatedPaths)"/>
			<FilesToExclude Include="@(ReferenceSatellitePaths)"/>
			<ReferenceCopyLocalPaths Remove="@(FilesToExclude)"/>
		</ItemGroup>

		<Message Text="Excluded Files @(FilesToExclude -> '%(FileName)%(Extension)', ', ')"
				 Importance="high"/>
	</Target>
	<Target Name="RemoveUnusedCopiedfiles" AfterTargets="CopyFilesToOutputDirectory">
		<!-- Remove *.xml, *.pdb, other unused files that copied from packages-->
		<ItemGroup>
			<FileToDelete Include="@(_SourceItemsToCopyToOutputDirectory -> '$(OutputPath)%(FileName)%(Extension)')" Condition="%(Extension) == '.pdb' OR %(Extension) == '.xml'"/>
		</ItemGroup>
		<Delete Files="@(FileToDelete)"/>		
		<Message Text="Deleted Files @(FileToDelete -> '%(FullPath)', ', ')"
				 Importance="high"/>
					   
		<!-- Remove other unused files -->
		<Delete Files="$(MSBuildProjectDirectory)\$(MSBuildProjectName).nuspec"/>
	</Target>
```

Well, If there's any enhancement to code above. you can post it here and close the issue in meantime.
