### ISSUE TITLE
DateTimeOffset property function

### ISSUE THREAD

**Issue by ghogen** [dotnet/msbuild#7504]
### Issue Description

This is a request for DateTimeOffset to be available as a property function.

### Steps to Reproduce

```xml
<Project>

<PropertyGroup>
  <Today>$([System.DateTime]::Now)</Today>
  <Today2>$([System.DateTimeOffset]::Now)</Today2>
</PropertyGroup>

<Target Name="Print">
  <Message Text="$(Today) $(Today2)"/>
</Target>

</Project>
```

**Comment by rainersigwald** [comment]
@gmarbury, can you give an example of how you'd like to use this in your build? In general, accessing time in a build is a source of nondeterminism that people prefer to avoid.

**Comment by gmarbury** [comment]
To provide a "Build Date" in an about box of a released multi-platform product. The build date is inserted as a single line in an embedded resource with MSBuild during "release" compilation. The About Box page looks for this resource and displays the information. What's nice about using MSBUild is it works on all platforms. Because of determinism, the timestamp in the PE header is useless. 

By the way, DateTime.Now work,  but because the build machines can be in different time zones or UTC, it would be nice to know the offset too.

Example
```
<PropertyGroup>
     <BuildDateTimeString>$([System.DateTimeOffset]::Now.ToString())</BuildDateTimeString>
</PropertyGroup>

<Target Name="WriteToBuildDate" BeforeTargets="CoreBuild">
        <WriteLinesToFile File="$(BuildDatePath)" Lines="$(BuildDateTimeString)" Overwrite="true" Encoding="Unicode" /></Target>
```

**Comment by jrdodds** [comment]
@rainersigwald, @BenVillalobos, This sounds similar to the work in #7428 and I would be happy to take this issue if that is agreeable. Thanks

**Comment by BenVillalobos** [comment]
Sounds good! Assigned to you
