### ISSUE TITLE
Option to fail builds when a ProjectReference does not exist

### ISSUE THREAD

**Issue by Eli-Black-Work** [dotnet/msbuild#7528]
I have a project, `MyApp`, that depends on a source generator project, `MySourceGenerator`, like so:

`MyApp.csproj`:
```xml
...
<ItemGroup>
	<ProjectReference Include="..\MySourceGenerator\MySourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" />
</ItemGroup>
...
```

`MySourceGenerator` generates a class that code in `MyApp` relies on. If `MySourceGenerator` isn't found, `MyApp` fails to build, because the class that it expects `MySourceGenerator` to emit is missing, but it's difficult to find the root of the issue, because the missing project reference shows up as a warning instead of an error: `"warning : The referenced project '..\MySourceGenerator\MySourceGenerator.csproj' does not exist."`

I'd like to request a feature to be able to mark a `<ProjectReference>` as required, so that if it's missing, an error would be shown instead of a warning 🙂

**Comment by Forgind** [comment]
Sounds reasonable to me, though that shouldn't be taken as the team signing off. I think all you'd have to do is add an error corresponding to [this warning](https://github.com/dotnet/msbuild/blob/65cb4d29255ae23c07203d10c99c993fe6ee0671/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2061-L2063) and give them complementary conditions based on whether it's in some "MSBuildUnskippableProjectReference" property.

**Comment by Nirmal4G** [comment]
First of all, why is it a warning instead of an error? Anything that doesn't exist should give out an error, not warning. So that it would prompt us to look into it and fix them.

**Comment by BenVillalobos** [comment]
Team Triage: Adding a better error code for missing project references makes a lot of sense. What is the scenario that your `MySourceGenerator.csproj` is missing entirely?

**Comment by Bosch-Eli-Black** [comment]
@BenVillalobos I think I had been manually modifying `MyApp.csproj` and messed up the path to `MySourceGenerator.csproj`

**Comment by Bosch-Eli-Black** [comment]
Actually, maybe I had incorrectly resolved some conflicts when applying a Git stash.

Either way, just user error, but would still be nice to show an error instead of a warning 🙂

**Comment by BenVillalobos** [comment]
@Bosch-Eli-Black sounds good :) retitled and triaged accordingly.

**Comment by Nirmal4G** [comment]
I also suggest that only project references that are part of the build pipeline should emit error, others can emit a warning. Since, I have seen projects that generate projects on the fly or some that are not actually referenced but uses non-compiled assets from referenced projects' intermediate build.

So, we can use `ReferenceOutputAssembly`, `OutputItemType` and other metadata to check if the project reference is actually needed!

**Comment by BenVillalobos** [comment]
@Nirmal4G I see, I can envision some logic in Common.CurrentVersion.Targets contain some sort of `<Error Condition="@(ProjectReference.Identity != '' and !Exists(%(ProjectReference.Identity)) and '%(ProjectReference.ReferenceOutputAssembly)' == 'true'"/>` 

The message would imply "you're saying you need binaries out of this thing, but we can't build it because _it doesn't exist_, what gives?"

**Comment by Bosch-Eli-Black** [comment]
I'm not sure I followed the above discussion, but if possible, I think it'd make sense for missing source generators to by default emit an error, instead of a warning 🙂

**Comment by Nirmal4G** [comment]
@BenVillalobos Yep, that's a start.

**Comment by kaylumah** [comment]
Any update on this one? Came across this issue after a user error in one of our projects. Was expecting that it would have failed the build, but it did not

**Comment by patrickserrano** [comment]
Just ran into this issue today, and would love to know if there are any updates?
