### ISSUE TITLE
MSBuild: dependencies and parallel builds

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/msbuild#7653]
Moved from https://developercommunity.visualstudio.com/t/MSBuild:-dependencies-and-parallel-build/10040724

Hi,

even though it’s more a nuisance, I consider it an error since it’s a missed optimization.

Here’s the problem: when building solutions with many projects from VS on a machine with many processors, then MSBuild mostly parallelizes poorly, since it linearizes the project-dependency-graph.

I observe then the following behavior:

Before the build starts, MSBuild  linearizes the project-dependency-graph and assigns each project to a processor. And then each processor builds its projects in a strict linear order.

That usually results in parallel builds, where processors stall to build on, because they are waiting for a dependency to finish its build, even though there are unbuilt projects where all dependencies are already built!

A much better way, would be to NOT linearize the project-dependency-graph, but to check dynamically (i.e. during the build) for “ready-to-build” projects and then dispatch them to the next available processor.

If there question to my request, please let me know.

Thanks

**Comment by yuehuang010** [comment]
Do you have a specific example in mind?  Is the "[graph](https://github.com/dotnet/msbuild/blob/main/documentation/specs/static-graph.md)" feature what you are describing? 

I think the fundamental issue is that once a project is loaded onto a node, it sticks to that node.  Overall this isn't an major issue because the tasks on nodes can "yield" or context switch to other projects.  Long running tasks don't block other projects from gaining access to the node.  For example, in VCXProj, once cl.exe spawns, the task yields, allowing other projects to work on something else.  Sadly "yield" isn't on by default as it would be a breaking change.  I do wish Exec task has yield on by default.

**Comment by rainersigwald** [comment]
I'm going to close this; the OP is not an accurate description of the current scheduler without `-graph` and `-graph` does change the scheduling.
