### ISSUE TITLE
Items returned by tasks not considered for EmbedInBinlog

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#7665]
I'd expect this to embed `C:\temp\1.txt` into the binlog, but it doesn't:

```
<Project>

  <Target Name="Build">
    <MSBuild Projects="$(MSBuildThisFileFullPath)" Targets="GetItems">
      <Output TaskParameter="TargetOutputs" ItemName="EmbedInBinlog" />
    </MSBuild>
  </Target>

  <Target Name="GetItems" Returns="@(ResultItem)">
    <ItemGroup>
      <ResultItem Include="C:\temp\1.txt" />
    </ItemGroup>
  </Target>
  
</Project>
```

As a workaround to fix this, also need to add an explicit ItemGroup:
```
<Project>

  <Target Name="Build">
    <MSBuild Projects="$(MSBuildThisFileFullPath)" Targets="GetItems">
      <Output TaskParameter="TargetOutputs" ItemName="EmbedInBinlog" />
    </MSBuild>
    <ItemGroup>
      <EmbedInBinlog Include="@(EmbedInBinlog)" />
    </ItemGroup>
  </Target>

  <Target Name="GetItems" Returns="@(ResultItem)">
    <ItemGroup>
      <ResultItem Include="C:\temp\1.txt" />
    </ItemGroup>
  </Target>
  
</Project>
```

I think this line:
https://github.com/dotnet/msbuild/blob/f1dae6ab690483458d37b8900f1d1e4a5fc72851/src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs#L521

should also allow for `TaskParameterMessageKind.TaskOutput`

**Comment by MeikTranel** [comment]
Well good news is @KirillOsenkov was absolutely right it really just way that TaskOutput that needed to be added to the filter.

![image](https://user-images.githubusercontent.com/6466560/171508233-ddb90d2b-2bbf-49a2-89c7-5e119c36ff60.png)

On the more bad news side i'm having trouble writing a test for this one and i really think the binary log deserves some love there (only a single test confirming parallel and console loggers are roundtripping - otherwise no test coverage for binary log contents).

I'd like some guidance regarding the BinaryLogs created by the `TestEnvironment` / `ObjectModelHelper`  in the following code:
<details>
  <summary>BinaryLogger_Tests.cs</summary>

  ```csharp
 [Fact]
public void BinaryLoggerShouldEmbedFilesViaTaskOutput()
{
    using var buildManager = new BuildManager();
    var binaryLogger = new BinaryLogger()
    {
        Parameters = $"LogFile={_logFile}",
        CollectProjectImports = BinaryLogger.ProjectImportsCollectionMode.Embed
    };

    var testProject = @"
<Project>
  <Target Name=""Build"">
    <MSBuild Projects=""$(MSBuildThisFileFullPath)"" Targets=""GetItems"" >
      <Output TaskParameter=""TargetOutputs"" ItemName=""EmbedInBinlog"" />
    </MSBuild>
  </Target>

  <Target Name=""GetItems"" Returns=""@(ResultItem)"">
    <CreateItem Include=""../**/*"">
        <Output TaskParameter=""Include"" ItemName=""ResultItem"" />
    </CreateItem>
  </Target>
</Project>";
    ObjectModelHelpers.BuildProjectExpectSuccess(testProject, binaryLogger);

    //Replay and verify file entries
    var logReader = new BinaryLogReplayEventSource();
    var files = new List<string>();
    logReader.AnyEventRaised += (object sender, BuildEventArgs e) =>
    {
        if (e is ProjectImportedEventArgs importArgs)
        {
            files.Add(importArgs.File);
        }
    };
    logReader.Replay(_logFile);
}
  ```
  
When i open the log written by the following code the entire thing looks like a light binlog - no parameter logging nothing.
  
![image](https://user-images.githubusercontent.com/6466560/171511652-11a3ba4d-9641-4f8b-87fd-ddd280ff1808.png)

 If i run `dotnet build /bl` over the same temporary project file everything is where it is expected - see above.
</details>

**Comment by KirillOsenkov** [comment]
could it be we need to set the verbosity to diagnostic inside BuildProjectExpectSuccess?

**Comment by MeikTranel** [comment]
I already tried setting `BinaryLogger.Verbosity` to `Diagnostic` to no avail - is there another verbosity setting somewhere i'm missing? I'm also not sure which of the APIs i'm supposed to use for running a simple project build with a binarylogger attached that i can parse for events later on. Maybe @rainersigwald has some guidance?

**Comment by MeikTranel** [comment]
Jesus somebody is pretty petty under that issue - how did they manage to link 1500 PRs to that issue :D:D

Have you looked at the problem regarding tests and binary logs ? Wanted to give it another look after work today.

Make sure to expand the spoiler section: https://github.com/dotnet/msbuild/issues/7665#issuecomment-1144206481

**Comment by MeikTranel** [comment]
I think i found a good solution to have some test coverage - sorry that it took so long - got super distracted and kind of forgot that i still had this laying around.
