### ISSUE TITLE
RoslynCodeTaskFactory doesn't support code fragment in separate file

### ISSUE THREAD

**Issue by JVimes** [dotnet/msbuild#7730]
### Issue Description

Code fragments in a separate file (as opposed to inline) work in CodeTaskFactory and based on the docs I expect them to work in RoslynCodeTaskFactory. But RoslynCodeTaskFactory fails to wrap the fragment in a Microsoft.Build.Utilities.Task, resulting in:

> error CS8805: Program using top-level statements must be an executable

The [docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2022#code-element) say:

> ...you can use the Source attribute of the Code element to specify the location of a file that contains the code for your task. The code in the source file must be of the type that is specified by the Type attribute.

My `Type` attribute is "Fragment".

### Example

```xml
<UsingTask TaskName="SplitPath"
           TaskFactory="RoslynCodeTaskFactory"
           AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >
    <ParameterGroup>
        <Path ParameterType="System.String" Required="true" />
        <Leaf ParameterType="System.String" Output="true" />
        <BasePath ParameterType="System.String" Output="true" />
    </ParameterGroup>
    <Task>
        <Code Type="Fragment"
              Language="cs"
              Source="$(MSBuildThisFileDirectory)\SplitPath.cs"/>
    </Task>
</UsingTask>
```

_SplitPath.cs:_

```c#
var charsToTrim = new char[] { '\\', '/' };
var trimmedPath = Path.TrimEnd(charsToTrim);
Leaf = System.IO.Path.GetFileName(trimmedPath);
BasePath = System.IO.Path.GetDirectoryName(trimmedPath);
```

The .tmp file given to csc.exe is:

```c#
var charsToTrim = new char[] { '\\', '/' };
var trimmedPath = Path.TrimEnd(charsToTrim);
Leaf = System.IO.Path.GetFileName(trimmedPath);
BasePath = System.IO.Path.GetDirectoryName(trimmedPath);
```

If I make the code inline, then the .tmp file is:

```c#
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InlineCode {
    using Microsoft.Build.Framework;
    using Microsoft.Build.Utilities;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;
    
    
    public class SplitPath : Microsoft.Build.Utilities.Task {
        
       // ...some code removed for readability...
        
        public override bool Execute() {

var charsToTrim = new char[] { '\\', '/' };
var trimmedPath = Path.TrimEnd(charsToTrim);
Leaf = System.IO.Path.GetFileName(trimmedPath);
BasePath = System.IO.Path.GetDirectoryName(trimmedPath);
foo

            return Success;
        }
    }
}
```

### Versions & Configurations

- MSBuild: 17.3.0.27701 (17.3.0-preview-22277-01+f1dae6ab6 for .NET Framework)
- dotnet.exe: 6.0.400-preview.22301.10
- Windows: Windows 10, Version 21H2 (OS Build 19044.1766)

**Comment by rainersigwald** [comment]
Nice bug report @JVimes, nice find @KalleOlaviNiemitalo.

Team triage: that looks broken! Marking for the backlog and up-for-grabs; we would happily accept a fix.

**Comment by jrdodds** [comment]
@rainersigwald I'm looking into this issue and also #7842. Although it does appear that #7842 is a different issue, it also appears to be in the same area of code as this issue.

**Comment by jrdodds** [comment]
`Source` and `Type` are not exclusive of each other and the problem appears to be the `else` at line 445 which prevents processing the `Type` when `Source` is provided.
https://github.com/dotnet/msbuild/blob/e1de0c476fac967bd1f1d4c17e5c8a70513cfdee/src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs#L432-L462

**Comment by jrdodds** [comment]
In the log output is an error:
```
error MSB4175: The task factory "RoslynCodeTaskFactory" could not be loaded from the assembly "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Build.Tasks.Core.dll". The task factory must return a value for the "TaskType" property.
```
This error message is misleading. Essentially an exception is thrown and the catch is reporting the MSB4175. There is no issue with loading the RoslynCodeTaskFactory  and the TaskType is not set because the inline code failed to compile.

The experience of writing inline tasks could be improved with error messaging that is more 'on point'. There is an issue for this error messaging. See #6419.

**Comment by jrdodds** [comment]
With the `RoslynCodeTaskFactory`, a MSB4175 `TaskFactoryLoadFailure` will be logged for the following types of errors which are not `TaskFactoryLoadFailure` errors:
- The inline task code has one or more compilation errors.
- The inline task code is in an external file (specified with `Source`) and the file can't be found or read.
- The inline task code is a class and the class name and the task name don't match.

(This list may not be complete.)

Because the catch that generates the logging of the MSB4175 is in `RegisteredTaskRecord`, the same issues appear to apply to `CodeTaskFactory`.

Regarding compilations errors:
Both `RoslynCodeTaskFactory` and `CodeTaskFactory` will log compilation errors. `CodeTaskFactory` will log compilation errors as MSB3758 `CodeTaskFactory.CompilerError`. However, `RoslynCodeTaskFactory` doesn't. Compilations errors are just generic errors with no MSB#### code.
