### ISSUE TITLE
In VS2022 Extension VSIX project why is the '.vsix' file Not getting created (and also some warnings)

### ISSUE THREAD

**Issue by garevaul** [dotnet/msbuild#7966]
Hi @rainersigwald,

In this .Net6.0-Windows VS2022 VSIX Extension Project which I have given the Link below, when I build the project, the '.vsix' file is not getting created. Only the project's '.dll' file is getting created.

https://1drv.ms/u/s!AjNAB3KpbqsEkW5cDsD_kQ4hBKsN?e=OnRqMd

PLEASE NOTE :: I have used Uprade-Assistant on my old VSIX project and got this project. Is that the correct way?

Also in addition to the issue above, when we compile it, then in the Visual Studio Output Window (the last few lines), we get warnings like this one::

1>D:\Goodbyte VSIX\GoodbyteHelperExtension\GoodbyteHelperExtension.csproj : warning NU1701: Package 'Microsoft.VisualStudio.Editor 17.0.491' **was restored using '.NETFramework,Version=v4.6.1,** .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' **instead of the project target framework 'net6.0-windows7.0'. This package may not be fully compatible with your project**.

Regards
Garevaul

**Comment by garevaul** [comment]
This question has been shifted to VSExtensibilty section located at this link::

https://github.com/microsoft/VSExtensibility/issues/128

**Comment by ayrtonmassey** [comment]
Commenting here because this is the first result that shows up when you search `vsix project does not output vsix file`.

Problem:
- My VSIX project no longer outputs a `.vsix` file.
- If I create a new VSIX project from the "VSIX project" template in VS2022, that project _does_ output a `.vsix` file, so the issue is with my project.

Solution:
My VSIX project had been converted to an SDK-style project:
```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
...
```
Visual Studio does not support many VSIX development features for SDK-style projects (e.g. you cannot open the `.vsixmanifest` project in the designer editor). 

You can fix the issue by converting back to the old project style, which is still used by the "VSIX Project" template. Create a new project using this template and diff the `.csproj` files if you need an example.

See also https://github.com/Microsoft/VSProjectSystem/issues/257
