### ISSUE TITLE
VS 2022 - Only JSON files are copied to the bin folder after Solution build

### ISSUE THREAD

**Issue by argelj289** [dotnet/msbuild#7978]
### Issue Description

Is there a reason why the project build don't include the other files generated by Angular CLI's ng build?

it only includes JSON files but the other files e.g. JS files are not included on the BIN folder

Refer to related link below:

https://stackoverflow.com/questions/73717625/asp-net-razor-pages-angular-dist-files-not-copying-to-bin-folder?noredirect=1#comment130193108_73717625

https://stackoverflow.com/questions/73699810/asp-net-razor-pages-dist-folder-getting-removed-during-build

### Steps to Reproduce

Steps:
- Open project in VS 2022 preview
- execute Solution build so that the csproj that contains NPM commands will generate the Angular 14 build files
- Wait for build to finish
- Check bin folder

I tried this sample below and changed the <targetframework> value of it to net6.0 and just removed the target named "CopyPartials" from the csproj upon pulling the source code:
https://github.com/AlahmadiQ8/RazorPagesAngular

### Expected Behavior

Angular 14 build files to be included on ASP.NET Razor Pages build files

### Actual Behavior

Angular 14 build files not included on ASP.NET Razor Pages build files and only sees JSON files on the BIN folder

### Analysis

I don't know where the fault is. its beyond my knowledge

**Comment by BenVillalobos** [comment]
> execute Solution build so that the csproj that contains NPM commands will generate the Angular 14 build files

This is a giveaway to me that MSBuild "didn't see" those files when it was looking for files.

I wrote up a gist on this problem here: https://gist.github.com/BenVillalobos/c671baa1e32127f4ab582a5abd66b005 

Basically, you might want to create a target that adds these generated files like in the example.

It also got merged into our docs here (I think the gist is easier to read, but I'm biased): https://learn.microsoft.com/visualstudio/msbuild/customize-your-buildhandle-generated-files

Does that help?
