### ISSUE TITLE
target runs twice during a single build

### ISSUE THREAD

**Issue by codingdave** [dotnet/msbuild#8033]
### Issue Description

My target runs twice during a single build when invoking a project file. That is not what I expect to happen according to [the msbuild documentation](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-targets?view=vs-2022)

I have attached a minimal sample [TargetsLoadBehavior.zip](https://github.com/dotnet/msbuild/files/9735589/TargetsLoadBehavior.zip)  that showcases the issue. My question is if this is a bug on MsBuild side or a bug in my code. 

### Steps to Reproduce

dotnet restore on the solution works fine:
```
dotnet restore .\TargetsLoadBehavior.sln -noAutoResponse
  * child: Loaded  child: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\children\Directory.Build.props'
  * child: Loaded  child: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\children\Directory.Build.targets'
  * child: Loaded parent: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\Directory.Build.targets'
  * child: Loaded  other: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\children\OtherTarget.targets'
  * parent: Loaded parent: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\Directory.Build.targets'
  Determining projects to restore...
  All projects are up-to-date for restore.
```

dotnet restore on the child project I can see that several targets are executed twice (highlighted with `<first time` and `<second time`:
```
dotnet restore .\children\child\child.csproj -noAutoResponse
  * child: Loaded  child: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\children\Directory.Build.props'   <first time
  * child: Loaded  child: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\children\Directory.Build.targets' <first time
  * child: Loaded parent: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\Directory.Build.targets'          <first time
  * child: Loaded  other: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\children\OtherTarget.targets'     <first time
  * child: Loaded  child: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\children\Directory.Build.props'   <second time
  * child: Loaded  child: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\children\Directory.Build.targets' <second time
  * child: Loaded parent: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\Directory.Build.targets'          <second time
  * child: Loaded  other: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\children\OtherTarget.targets'     <second time
  Determining projects to restore...
  All projects are up-to-date for restore.
```

### Expected Behavior
I would expect no invokation of the items that I marked as `<second time`

### Actual Behavior
Some targets run twice during a single build

### Versions & Configurations
dotnet --version
6.0.401

For completeness, although this issue is independent of the msbuild executable and VS 2022
msbuild -version
MSBuild version 17.3.0+f67e3d35e for .NET Framework
17.3.0.37102

### Additional context
I use MsBuild to configure a branding mechanism for a complex application. In my usecase "children" contains the fully functional base application with all its projects. If a parent is present, the base application will be branded with the information (MsBuild) and behavior (.cs code) of the parent. (The build of the base application will be different than if no parent is available).

The base application uses Directory.Build.props and Directory.Build.targets for its global configuration. Extensibility is given by overriding properties. The branding (parent) application uses its own Directory.Build.props and Directory.Build.targets files. When the child projects are built they need to detect that they have a parent by using [Multi Level Merging](https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#use-case-multi-level-merging).

I hope the code, the output, and the usecase are clear. 
Kind regards
Dave

**Comment by yuehuang010** [comment]
It is running again because the second instance has different Properties.  This will in turn spawn a new evaluation and build instance, thus a fresh set of targets.  I am pretty sure this is documented somewhere, but I couldn't find it.  The second instance has ExcludeRestorePackageImports=true property, added in Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets. 

I think the issue is using "InitialTargets" as a way to invoke your target.  I don't recommend doing anything heavy in InitialTargets as it will be run on every instance.  Instead, move your attachment point to be part of the actual Compile chain.  IE. BeforeTargets="Build".

**Comment by codingdave** [comment]
I don't see why the second instance has different properties. Nothing has changed except that I call the child.

I am not doing anything heavy in the Initial targets. I use them to debug loading and invocation of my MsBuild setup.

I tried using BeforeTargets="Restore;Build" instead of using InitialTargets but that seems to fail for the target ParentDirectoryBuildTarget (parent/Directory.Build.targets), [see here](https://github.com/dotnet/msbuild/files/9771289/TargetsLoadBehavior_BeforeTargets_Restore_Build.zip) for which I don't see the Loading message.

Hoewever, I found out that the issue is a bit different and has nothing to do with parent/child or multi-level merging. Instead MsBuild behaves differently when calling the sln to calling the csproj (when
 [using InitialTargets](https://github.com/dotnet/msbuild/files/9771436/TargetsLoadBehavior_parent_InitialTargets.zip)):

```
dotnet restore .\TargetsLoadBehavior.sln -noAutoResponse
  * parent: Loaded parent: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\Directory.Build.targets'
  Determining projects to restore...
  All projects are up-to-date for restore.
```

```
dotnet restore .\parent\parent.csproj -noAutoResponse
  * parent: Loaded parent: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\Directory.Build.targets'
  * parent: Loaded parent: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\Directory.Build.targets'
  Determining projects to restore...
  Restored E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\parent\parent.csproj (in 85 ms).
```

When I remove InitialTargets I still see a different behavior when invoking the project vs the solution (when [using BeforeTargets Restore](https://github.com/dotnet/msbuild/files/9771426/TargetsLoadBehavior_parent_BeforeTargets_Restore.zip)):


```
dotnet restore .\TargetsLoadBehavior.sln -noAutoResponse
  Determining projects to restore...
  All projects are up-to-date for restore.
```

```
dotnet restore .\parent\parent.csproj -noAutoResponse
  Determining projects to restore...
  * parent: Loaded parent: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\Directory.Build.targets'
  All projects are up-to-date for restore.
```

**Comment by rainersigwald** [comment]
What you're encountering is basically a quirk of the NuGet implementation of `Restore`.

NuGet collects `PackageReference` items from a loaded/evaluated copy of the project, then restores the referenced packages. However if done naively, this can lead to a very confusing behavior: a package (say `ReferencedPackage` can include MSBuild logic that has `<PackageReference Include="SomeOtherPackage" />`, so

1. On a clean repo, the restore would see only `ReferencedPackage`, and restore it.
2. If you ran restore again, the restored build logic would be used, and the list of referenced packages would be `{ReferencedPackage, SomeOtherPackage}`.
3. That potentially recurses! So there's no way to actually know "we are done restoring".

To solve this problem, NuGet collects `ProjectReference`s in a special mode, specifying the global property `ExcludeRestorePackageImports = true`. The imports of package-delivered build logic are conditioned on that property, so are not considered when getting the list of packages.

Since your target is an `InitialTargets`, it runs _every time the project is built for any reason_.

The first time it runs is when the desired target is `Restore`, so the InitialTargets runs (in the instance of `child.csproj` that has no global properties set. Then the Restore target starts to run, and invokes a target inside `child.csproj` (but in a new instance with `ExcludeRestorePackageImports = true`). As _that_ starts to run, it first runs the InitialTargets, including your target, then runs the target that reports `PackageReference`s.

It is generally a bad idea to use `InitialTargets`, for exactly this reason. If you instead hook `BeforeTargets="BeforeBuild"` or similar, your target won't be run in the NuGet-implementation-detail builds that collect `PackageReference` information.

**Comment by codingdave** [comment]
Thanks @rainersigwald, I spend some time reading MsBuild evaluation to understand your answer. I see that InitialTargets should better not be used. (Isnt there a deprecation way for MsBuild?)

But can you explain my last finding from above: Why do I get different results from compiling the sln vs the csproj?

> When I remove InitialTargets I still see a different behavior when invoking the project vs the solution (when [using BeforeTargets Restore](https://github.com/dotnet/msbuild/files/9771426/TargetsLoadBehavior_parent_BeforeTargets_Restore.zip)):

```
dotnet restore .\TargetsLoadBehavior.sln -noAutoResponse
  Determining projects to restore...
  All projects are up-to-date for restore.
```

```
dotnet restore .\parent\parent.csproj -noAutoResponse
  Determining projects to restore...
  * parent: Loaded parent: 'E:\Projects\bugreportsAndSamples\MsBuild\TargetsLoadBehavior\Directory.Build.targets'
  All projects are up-to-date for restore.
```
