### ISSUE TITLE
.NET 7 RC1+ - unable to build/run project after stopping it

### ISSUE THREAD

**Issue by danfma** [dotnet/msbuild#8071]
### Description

After the first RC of .NET 7, after running and stopping a .NET process, the dotnet runtime will keep the MSBuild running and it will block any attempt to run or build any project after that.

![image](https://user-images.githubusercontent.com/101121/196423127-b0537c6d-d354-4ca4-9e9c-2973744ed67a.png)

### Reproduction Steps

- Run any project with or without watch mode;
- Stop the execution after some time;
- Try to run the project again.

### Expected behavior

I expect to be able to run/build any other project again.

### Actual behavior

The dotnet tool gets blocked by a previous build running on background.

### Regression?

It worked until before the .NET 7 RC1.

### Known Workarounds

I have to kill all running .NET processes with a MSBuild.dll.
The easy way, `killall dotnet`.

### Configuration

![image](https://user-images.githubusercontent.com/101121/196423034-a97fec0f-8674-435e-a83e-0411924ad767.png)

**Comment by baronfel** [comment]
This is probably the MSBuild Server feature not responding to cancellation correctly. We may have fixed this for RC2, but in either case the feature has been disabled for the GA release. For RC1 you can set the environment variable DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER` to `true` to disable the feature. You can also kill the MSBuild Server processes with `dotnet build-server shutdown` instead of forcibly killing all dotnet processes.

**Comment by rainersigwald** [comment]
It was not fixed for RC2, but is off by default for 7.0.100 final GA.

**Comment by rokonec** [comment]
This has most likely been fixed by https://github.com/dotnet/msbuild/pull/8006 which will be released in GA.
I am closing this issues as fixed. Please feel free to reopen it if you experience this bug after GA.
Thank you very much for reporting this bug.
