### ISSUE TITLE
Consider adding a `WithoutMetadataValue` msbuild item function

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/msbuild#8205]
The following set of [item functions](https://learn.microsoft.com/en-us/visualstudio/msbuild/item-functions?view=vs-2022) allow to condition on or filter items based on metadata:
- AnyHaveMetdataValue
- HasMetadata
- WithMetadataValue

These functions make it super simple to include items or condition based on metadata during evaluation time, without the need of batching (inside a target).

Over the last years I often wished that there would also be a `WithoutMetadataValue` item function so that the following pattern wouldn't require an extra target:

```xml
<Target Name="GetCompileFilteredItems">
  <ItemGroup>
    <CompileFiltered Include="@(Compile->WithMetadataValue('ExcludeFromX', ''))" />
    <CompileFiltered Include="@(Compile->WithMetadataValue('ExcludeFromX', 'false'))" />
  </ItemGroup>
</Target>

<Target Name="X"
             Inputs="@(CompileFiltered)"
             Outputs="..."
             DependsOnTargets="GetCompileFilteredItems">
  ...
</Target>
```

Instead, with a `WithoutMetadtaValue` item function, the filtering can happen just in-time without a separate target.
```xml
<Target Name="X"
             Inputs="@(Compile->WithoutMetadataValue('ExcludeFromX', 'true'))"
             Outputs="...">
  ...
</Target>
```

**Comment by JaynieBai** [comment]
I'd like to do this. Assigned it to me now.

**Comment by JaynieBai** [comment]
Here，we expect to return the items which don't have the metadata value when the metadata name is given. For example， we expect message with **[One|Three]** ? @ViktorHofer 
```<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		<_Item Include="One">
			<A>true</A>
		</_Item>
		<_Item Include="Two">
			<A>false</A>
		</_Item>
		<_Item Include="Three">
			<A></A>
		</_Item>
		<_Item Include="Four">
			<B></B>
		</_Item>
	</ItemGroup>

	<Target Name="AfterBuild">
		<Message Text=" [@(_Item->WithoutMetadataValue('A', 'false'), '|')]"/>
	</Target>
</Project>```

**Comment by ViktorHofer** [comment]
> Here，we expect to return the items which don't have the metadata value when the metadata name is given. For example， we expect message with [One|Three] when build the following project?

I would expect `WithoutMetadataValue` to return the inverse of items of the `WithMetadataValue`. In your above example, the following output would be printed: `[One|Three|Four]`.

**Comment by JaynieBai** [comment]
> > Here，we expect to return the items which don't have the metadata value when the metadata name is given. For example， we expect message with [One|Three] when build the following project?
> 
> I would expect `WithoutMetadataValue` to return the inverse of `WithMetadataValue`. In your above example, the following output would be printed: `[One|Three|Four]`.

I see. Thank you. In your above example,when we want to `<Message Text=" [@(_Item->WithoutMetadataValue('A', ''), '|')]"/>`, it will print `[One|Two|Four]`. Our current [GetMetadataEscaped(string metadataName)](https://github.com/dotnet/msbuild/blob/06231decdb6530a9e98d752f2a90661f66e7a229/src/Build/Instance/ProjectItemInstance.cs#L1265) both GetMetadataEscaped("A") between "metadata not present" 
``<_Item Include="Four">
			<B></B>
</_Item> ``
and "present but set to null or the empty string"
`<_Item Include="Three">
			<A></A>
</_Item>` 
return emtpy.  @rainersigwald  just as you say in the issue https://github.com/dotnet/msbuild/issues/1030#issuecomment-247372036. MSBuild can't distinguish between "nonexistent" and null, but fixing that is a much larger project.  what's your opinion now?

**Comment by jrdodds** [comment]
@ViktorHofer's target `X` could be written as follows to eliminate the `GetCompileFilteredItems` target:

```XML
<Target Name="X"
             Inputs="@(Compile->WithMetadataValue('ExcludeFromX', ''));@(Compile->WithMetadataValue('ExcludeFromX', 'false'))"
             Outputs="...">
  ...
</Target>
```

But having a `WithoutMetadataValue` item function would be cleaner and more readable.

**Comment by jrdodds** [comment]
MSBuild can distinguish between "metadata not present" and "metadata present but set to an empty value" because the metadata names are known. See the [`MetadataNames` property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.framework.itaskitem.metadatanames?view=msbuild-17). But the implementations of the Item functions don't handle the distinction.

Starting from @JaynieBai's example code, here are a set of tests of item functions:

```XML
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <ItemGroup>
    <_Item Include="One">
      <A>true</A>
    </_Item>
    <_Item Include="Two">
      <A>false</A>
    </_Item>
    <_Item Include="Three">
      <A></A>
    </_Item>
    <_Item Include="Four">
      <B></B>
    </_Item>
  </ItemGroup>

  <Target Name="Tests" DependsOnTargets="WithMetadataValueAFalse;WithMetadataValueAEmpty;HasMetadataA;AnyHaveMetadataValueBEmpty;HasMetadataC;AnyHaveMetadataValueCEmpty;WithMetadataValueANotTrue" />

  <Target Name="WithMetadataValueAFalse">
    <Message Text=" [@(_Item->WithMetadataValue('A', 'false'), '|')]"/>
  </Target>

  <Target Name="WithMetadataValueAEmpty">
    <Message Text=" [@(_Item->WithMetadataValue('A', ''), '|')]"/>
  </Target>

  <Target Name="HasMetadataA">
    <Message Text=" [@(_Item->HasMetadata('A'), '|')]"/>
  </Target>

  <Target Name="AnyHaveMetadataValueB">
    <Message Text=" [@(_Item->AnyHaveMetadataValue('B', ''), '|')]"/>
  </Target>

  <Target Name="AnyHaveMetadataValueBEmpty">
    <Message Text=" [@(_Item->AnyHaveMetadataValue('B', ''), '|')]"/>
  </Target>

  <Target Name="HasMetadataC">
    <Message Text=" [@(_Item->HasMetadata('C'), '|')]"/>
  </Target>

  <Target Name="AnyHaveMetadataValueCEmpty">
    <Message Text=" [@(_Item->AnyHaveMetadataValue('C', ''), '|')]"/>
  </Target>

  <Target Name="WithMetadataValueANotTrue">
    <ItemGroup>
      <_Temp Include="@(_Item->WithMetadataValue('A', ''));@(_Item->WithMetadataValue('A', 'false'))"/>
    </ItemGroup>
    <Message Text=" [@(_Temp, '|')]"/>
  </Target>

</Project>
```

The output is:

```
WithMetadataValueAFalse:
   [Two]
WithMetadataValueAEmpty:
   [Three|Four]
HasMetadataA:
   [One|Two]
AnyHaveMetadataValueBEmpty:
   [true]
HasMetadataC:
   []
AnyHaveMetadataValueCEmpty:
   [true]
WithMetadataValueANotTrue:
   [Three|Four|Two]
Done Building Project "C:\Users\jrdodds\source\itemfunctions.proj" (default targets).
```

Note that `_Item->WithMetadataValue('A', '')` returns `Three;Four` and `_Item->HasMetadata('A')` returns `One;Two`. If the functions distinguished between present and not present, the outputs might reasonably be `Three` and `One;Two;Three`.

Note that `_Item->HasMetadata('C')` return no items but `_Item->AnyHaveMetadataValue('C', '')` returns `true`, i.e. `AnyHaveMetadataValue` is `true` for metadata that doesn't exist.

I view the apparent choice to not distinguish between existent but empty and non-existent as counter-productive but there could be a lot of code that depends on the current behavior of the current item functions.

**Comment by jrdodds** [comment]
MSBuild can distinguish between "metadata not present" and "metadata present but set to an empty value" because the metadata names are known. See the [`MetadataNames` property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.framework.itaskitem.metadatanames?view=msbuild-17). But the implementations of the Item functions don't handle the distinction.

Starting from @JaynieBai's example code, here are a set of tests of item functions:

```XML
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <ItemGroup>
    <_Item Include="One">
      <A>true</A>
    </_Item>
    <_Item Include="Two">
      <A>false</A>
    </_Item>
    <_Item Include="Three">
      <A></A>
    </_Item>
    <_Item Include="Four">
      <B></B>
    </_Item>
  </ItemGroup>

  <Target Name="Tests" DependsOnTargets="WithMetadataValueAFalse;WithMetadataValueAEmpty;HasMetadataA;AnyHaveMetadataValueBEmpty;HasMetadataC;AnyHaveMetadataValueCEmpty;WithMetadataValueANotTrue" />

  <Target Name="WithMetadataValueAFalse">
    <Message Text=" [@(_Item->WithMetadataValue('A', 'false'), '|')]"/>
  </Target>

  <Target Name="WithMetadataValueAEmpty">
    <Message Text=" [@(_Item->WithMetadataValue('A', ''), '|')]"/>
  </Target>

  <Target Name="HasMetadataA">
    <Message Text=" [@(_Item->HasMetadata('A'), '|')]"/>
  </Target>

  <Target Name="AnyHaveMetadataValueB">
    <Message Text=" [@(_Item->AnyHaveMetadataValue('B', ''), '|')]"/>
  </Target>

  <Target Name="AnyHaveMetadataValueBEmpty">
    <Message Text=" [@(_Item->AnyHaveMetadataValue('B', ''), '|')]"/>
  </Target>

  <Target Name="HasMetadataC">
    <Message Text=" [@(_Item->HasMetadata('C'), '|')]"/>
  </Target>

  <Target Name="AnyHaveMetadataValueCEmpty">
    <Message Text=" [@(_Item->AnyHaveMetadataValue('C', ''), '|')]"/>
  </Target>

  <Target Name="WithMetadataValueANotTrue">
    <ItemGroup>
      <_Temp Include="@(_Item->WithMetadataValue('A', ''));@(_Item->WithMetadataValue('A', 'false'))"/>
    </ItemGroup>
    <Message Text=" [@(_Temp, '|')]"/>
  </Target>

</Project>
```

The output is:

```
WithMetadataValueAFalse:
   [Two]
WithMetadataValueAEmpty:
   [Three|Four]
HasMetadataA:
   [One|Two]
AnyHaveMetadataValueBEmpty:
   [true]
HasMetadataC:
   []
AnyHaveMetadataValueCEmpty:
   [true]
WithMetadataValueANotTrue:
   [Three|Four|Two]
Done Building Project "C:\Users\jrdodds\source\itemfunctions.proj" (default targets).
```

Note that `_Item->WithMetadataValue('A', '')` returns `Three;Four` and `_Item->HasMetadata('A')` returns `One;Two`. If the functions distinguished between present and not present, the outputs might reasonably be `Three` and `One;Two;Three`.

Note that `_Item->HasMetadata('C')` return no items but `_Item->AnyHaveMetadataValue('C', '')` returns `true`, i.e. `AnyHaveMetadataValue` is `true` for metadata that doesn't exist.

I view the apparent choice to not distinguish between existent but empty and non-existent as counter-productive but changing the behavior of the current item functions
