### ISSUE TITLE
Huge memory consumption by running dotnet even with just a -? switch

### ISSUE THREAD

**Issue by z4v4l** [dotnet/msbuild#8404]
### Issue Description
When I type just `dotnet -?` or `dotnet build -?`, it makes huge memory consumption. the machine is Win7, the .NET is the latest.
here is a nicey screenshot, screwed up a bit by jpg though:

![dotnetbuildramhog](https://user-images.githubusercontent.com/17954954/216731927-413fa603-f8b0-4db5-ace4-30f59bf64040.jpg)

of 8GBs of RAM almost all is consumed, even though performance monitor shows 1 or 2 dotnet instances, each having around 600MB commit, but significantly smaller working sets (380KB of a private set, when running just `dotnet -?`). especially for the 2nd one. still, it gets noticeable, that the system pages out a lot, other programs lag after this (black rectangles on screen instead of their client areas). the disk is 5400rpm, not NVMe SSD.

### Steps to Reproduce
just typing `dotnet [build] -?` or biulding a simple "hello world" in the specified below environment is enough to reproduce it.

### Analysis
when running dotnet. both from CLI and VS. no more ideas.

looking at the screenshot, it's seen, that the amount increases (for several seconds duration), by 4GB. even though, the dotnet process commit is ~500MB. as said, the working set (any) is way smaller. if that is just a confusion of the counters, why other programs experience the lag, very well observable on the GUI? I don't know if modified time on the pagefile is an accurate measure of paging happened, but while posting this and making the screenshot, the pagefile modified time remained with 6 hours ago.

### Versions & Configurations
```
>msbuild -version
MSBuild version 17.4.1+9a89d02ff for .NET Framework
17.4.1.60106
```
dotnet CLI and VS IDE. the latest VS (downloaded yesterday).
Windows 7 x64.

### Regression?
I don't know, since I am a C guy and always have been using MSVC and nmake from command line.

**Comment by reflectronic** [comment]
.NET 7 is not supported on Windows 7. The large memory usage is a known bug that was marked wont-fix: https://github.com/dotnet/runtime/issues/79469.

**Comment by z4v4l** [comment]
> .NET 7 is not supported on Windows 7. The large memory usage is a known bug that was marked wont-fix: [dotnet/runtime#79469](https://github.com/dotnet/runtime/issues/79469).

but it's not a .Net app consuming it, it's the dotnet process does. and it's .Net 6.0 long term support.

**Comment by teo-tsirpanis** [comment]
MSBuild 17.4 runs on .NET 7. You should add a `global.json` file to your repository limiting the SDK version to 6.

**Comment by z4v4l** [comment]
> MSBuild 17.4 runs on .NET 7. You should add a `global.json` file to your repository limiting the SDK version to 6.

thank you. now, it's not only doesn't do 4-5GB commits, but runs instantly. If I put global.json file in a top directory that contains all my dotnet projects directories, would that be enough? I read, that it would, but the doc says "one of its parent directories". :)

**Comment by teo-tsirpanis** [comment]
It would work but I would recommend you to add it to each repository for consistency among all its developers.

**Comment by AR-May** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/79469

**Comment by FyiurAmron** [comment]
for posteriority:
set `DOTNET_EnableWriteXorExecute` env var to `0` ; it was an opt-in in .NET 6, but was default to `1` on .NET 7. It behaves absurdly on Win7 (memory consumption goes through the roof even if no process actually uses it), since it doesn't support it too well.

**Comment by Charles113** [comment]
".NET 7 is not supported on Windows 7. The large memory usage is a known bug that was marked wont-fix".
`set DOTNET_EnableWriteXorExecute=0` fixes the bug.
Our IT team got into huge trouble today because our server crashed since we migrated from .NET 6 to .NET 8 on a windows 7 terminal server.
On .NET 6, 30 users could use our app, on .NET 8 it crashed after 5 users because of the huge memory usage.

It took us a long time and resources to find the cause of this bug.

Not happy with the attitude "We don't care about a huge bug because it's windows 7".
Especially if it's that easy to fix. Or at least put a warning somewhere.

**Comment by hez2010** [comment]
> Not happy with the attitude "We don't care about a huge bug because it's windows 7". Especially if it's that easy to fix. Or at least put a warning somewhere.

This is not an easy fix from the perspective of the runtime. `EnableWriteXorExecute` is an essential security feature introduced since .NET 7 which can make sure a memory region never be both executable and writable. This can protect apps from potential vulnerability exploitations. Such feature requires system support at least Windows 10, .NET really cannot just "disable the essential security feature because users want to use it on an unsupported system".
