### ISSUE TITLE
DownloadFile hides exception information

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#8407]
https://hachyderm.io/@peterhuene/109819767121708226

https://github.com/dotnet/msbuild/blob/main/src/Tasks/DownloadFile.cs#L128

The task should log return HTTP code at bare minimum, and ideally much more error information.

**Comment by peterhuene** [comment]
For an actual useful report of the issue and not just my snarky hot take on social media, our CI on https://github.com/bytecodealliance/wasmtime-dotnet has been flaky on Windows (only, it seems) lately due to:

```
error MSB3923: Failed to download file "https://github.com/bytecodealliance/wasmtime/releases/download/dev/wasmtime-dev-aarch64-linux-c-api.tar.xz". Authentication failed, see inner exception.
```

Our CI uses the `DownloadFile` task to pull down different tarballs of Wasmtime's libraries on the supported platforms to create our NuGet package.

As it is a public GitHub URL that should not require authentication, it's likely that it's either a GitHub infrastructure issue or the download is being throttled and just so happens to fail this way.

However, without knowing what the inner exception contained, it is quite difficult to diagnose the underlying problem using the `DownloadFile` task as currently implemented.

**Comment by rainersigwald** [comment]
Reactivating per feedback: https://github.com/dotnet/msbuild/pull/8440#issuecomment-1437783713

**Comment by JaynieBai** [comment]
Fix in https://github.com/dotnet/msbuild/commit/18fe510422c6cf65533add0c82b9d4d190e5df28

**Comment by JaynieBai** [comment]
Fix in https://github.com/dotnet/msbuild/pull/8557
