### ISSUE TITLE
ProjectInstance should allow a way to specify Interactive

### ISSUE THREAD

**Issue by jeffkl** [dotnet/msbuild#8523]
NuGet's static graph-based restore is using the `ProjectInstance.FromFile()` method to create an instance of a `ProjectInstance`.  However, there is no way to specify the `Interactive` flag in any public constructor.  `internal` and `private` constructors derive this flag from the `BuildParameters` but there is no public constructor that accepts a `BuildParameters` object either.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Console/MSBuildStaticGraphRestore.cs#L929

This leads to static graph-restore not being able to set the `Interactive` flag so then restores can fail in certain cases when the configured credential provider needs to prompt the user for authentication.

I think the `ProjectOptions` class should just have a `Interactive` property which gets plumbed through.

Repro steps:
* Have a set of projects that reference NuGet-based MSBuild project SDKs and package references
* Configure a feed that requires authentication (like Azure DevOps Artifacts)
* Configure a credential provider that will get an authentication token via a prompt (like the Azure Artifacts Credential Provider)
* Enable static graph-based restores via `/p:RestoreUseStaticGraphEvaluation=true`
* Restore

This has been a problem for a few years but only recently did I have enough time to figure out why.

/cc @dfederm

**Comment by Forgind** [comment]
Since BuildParameters itself is public, and Interactive is a public property on BuildParameters, I was hopeful it might suffice to have BeginBuild(BuildParameters) start by tweaking _interactive, but it doesn't look like that's sufficient because ProjectInstance.FromFile itself calls Evaluate with the wrong Interactive value. My only real concern with tweaking ProjectOptions to have a (public) Interactive property is that since it isn't sealed, people might theoretically be extending it. It should be ok as long as we make it default to false, though.

Since you self-assigned this, I'm guessing you want to work on it?

**Comment by jeffkl** [comment]
> My only real concern with tweaking ProjectOptions to have a (public) Interactive property is that since it isn't sealed, people might theoretically be extending it. It should be ok as long as we make it default to false, though.

That's a good point, since its not sealed it could be extended.  But yes it should default to `false`

> Since you self-assigned this, I'm guessing you want to work on it?

Also yes, I was planning on working on this if the MSBuild team will accept it
