### ISSUE TITLE
[Bug]: Import fails when an expression evaluates to an empty string

### ISSUE THREAD

**Issue by jrdodds** [dotnet/msbuild#8622]
### Issue Description

An import with an expression should not fail when the expression evaluates to an empty string.

The following previously worked but now fails with an MSB4020 error if `GetPathOfFileAbove` returns an empty string (because there are no matching files).

```xml
  <Import Project="$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFile)', '$(MSBuildThisFileDirectory)../'))" />
```

The example `Import` could be added to every `Directory.Build.props` and `Directory.Build.targets` file.

The result of an expression can't be predetermined. An 'empty set' result must be allowed by `Import` as a no-op.

If an 'empty set' result is an error, then, to be robust, every `Import` would need to be rewritten as something like the following:

```xml
  <PropertyGroup>
    <FileToImport>$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFile)', '$(MSBuildThisFileDirectory)../'))</Empty>
  </PropertyGroup>
  <Import Project="$(FileToImport)" Condition="Exists('$(FileToImport)')" />
```

There is a case for an empty string never being an error.

e.g. Why should

```xml
  <Import Project="" />
```

and 

```xml
  <PropertyGroup>
    <Empty></Empty>
  </PropertyGroup>
  <Import Project="$(Empty)" />
```

have different results? And, since the `Project` attribute accepts a set, why is the empty set special?

It would be cleaner and more consistent to accept an empty set as valid and handle it as a no-op, regardless of whether it is an explicit empty string or the result of evaluating an expression.

To support the cases where an error is desired, an explicit `ProjectMustExist` attribute could be added to the `Import`.

### Steps to Reproduce

With a code tree create a Directory.Build.targets file with the following content:

```xml
<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFile)', '$(MSBuildThisFileDirectory)../'))" />
</Project>
```

In a directory above create a second Directory.Build.targets file but with empty content:

```xml
<Project>
</Project>
```

Build and note that the project/solution builds successfully.

Remove or rename the second Directory.Build.targets file.

Build and note that the project/solution now fails with an MSB4020 error.

### Expected Behavior

The following example should not fail regardless of the return value from `GetPathOfFileAbove`.

```xml
  <Import Project="$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFile)', '$(MSBuildThisFileDirectory)../'))" />
```

### Actual Behavior

When an expression is evaluated and the file is found to not exist, an MSB4020 is thrown. This breaks existing code.

### Analysis

This is a regression.

This appears to be a design issue. It appears that at some point the importance of supporting the empty set was overlooked and the assumption was made that an empty value is an error that should be trapped.

### Versions & Configurations

MSBuild version 17.5.1+f6fdcf537 for .NET Framework
17.5.1.16304

**Comment by rainersigwald** [comment]
I don't think I understand. Why do you think this should _not_ be an error?

**Comment by rainersigwald** [comment]
What I am hearing is that you'd like a new feature that allows empty imports, and you think it's justified by reducing the need for duplicating the same expression in the `Condition`. Is that a fair summary?

**Comment by jrdodds** [comment]
No, that doesn't summarize at all, but a new feature that allows empty imports is a compromise I can accept. :slightly_smiling_face:

My perspective is that the completeness and consistency of the set logic of the `Import` is broken because the empty set is disallowed. There is a comment in `BuildRequestDataFlags`:

```c#
        /// <summary>
        /// When this flag is present, projects loaded during build will ignore missing imports (<see cref="ProjectLoadSettings.IgnoreMissingImports"/> and <see cref="ProjectLoadSettings.IgnoreInvalidImports"/>).
        /// This is especially useful during a restore since some imports might come from packages that haven't been restored yet.
        /// </summary>
        IgnoreMissingEmptyAndInvalidImports = 1 << 6,
```

That a restore operation needs to disable erring on an empty set of imports is an indicator to me that this is a defect.

To turn it around, why should providing an empty set to `Import` be an error?

**Comment by jrdodds** [comment]
Supporting a list of files was added with #2014

**Comment by Forgind** [comment]
What concerns me is this sort of case:

```XML
<PropertyGroup>
    <PathToCriticalImport>foo</PathToCriticalImport>
</PropertyGroup>

<Import Projects="$(PathToCrticalImport)" />
```

In case that was unclear, I missed an 'i' when importing PathToCriticalImport. As far as MSBuild is concerned, that's a valid property, though an empty one. Then we try to import that, and we fail. Should we throw an error?

Per your suggestion here, the answer is no, but I think you'd agree the customer should somehow be informed that there's a typo. You suggested adding a `ProjectMustExist` attribute if we really do need it, but is that not cognitive load?

With current MSBuild, there is already a one-line solution to achieve what you want—adding a Condition as you mentioned. I do think no-Condition imports should be considered as required to be nonempty as a difference between them and conditional imports.

I will add that I consider the NuGet case very unusual. The Imports they ignore are important imports, and they should lead to errors if they never exist. The point is that they might not exist at the time they're evaluated because NuGet is still in the process of downloading all the PackageReferences. Outside of manually downloading files (like with our task), I don't see why a project file not existing should be considered ok.
