### ISSUE TITLE
API-using application is spawned instead of `dotnet` when using CodeTaskFactory

### ISSUE THREAD

**Issue by Leon99** [dotnet/msbuild#9052]
I'm trying to open csproj files via `Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenProjectAsync` from my console app. One of the projects, a rather big one, hangs the execution and spawns another instance of the app.

Tried both v4.6.0 from nuget.org and built myself from https://github.com/dotnet/roslyn/releases/tag/Visual-Studio-2022-Version-17.6.4, same behavior.

Tried to debug but quickly got lost... My best guess is that MSBuild is trying to create additional processes (for compilation?) to parallelize since it's a large project, but instead instantiates my app.
Any suggestions much appreciated.

**Comment by rainersigwald** [comment]
@Leon99 can you tell us more about your application--are you building it self-contained or single-file? are you running it with `application.exe` or `dotnet application.dll`?

If you're using `application.exe` can you please try running `application.dll`? I suspect that would work around the issue.

Background: `RoslynCodetaskFactory` invokes `dotnet csc.dll` to build the temporary task assembly. But what `dotnet` should it run? We try to run "the same one we're running in" . . . but it looks like we might be getting that wrong in your case and running `yourapplication.exe` instead of `dotnet.exe`.

**Comment by GangWang01** [comment]
Attached a sample  to repro this issue. 

For .NET version of msbuild, root cause is the following code couldn't set dotnet cli path correctly when running the application via `application.exe`. Rather than the path of dotnet.exe, it's wrongly set using the path of the applicaiton. https://github.com/dotnet/msbuild/blob/3050e91563b2b9bbafd820f4e8cd3d050dd9d21a/src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactoryCompilers.cs#L16-L18
For the repro sample, the fix is to modify dotnet cli path based on the environment variable `MSBUILD_EXE_PATH`  that is set when registering the .NET SDK instance. But Roman mentioned getting dotnet cli path from the environment variable is not reliable and may not work for all scenarios, like Visual Studio doesn't need to register the instance (Cc @rokonec, please correct me if anything wrong). Welcome suggestions on a good way to get dotnet cli path working for all scenarios.

As for .NET framework version of msbuild, the System.MissingMethodException is thrown out. This is related to https://github.com/dotnet/msbuild/issues/7873.
```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'.
  Source=Microsoft.Build
```

**Comment by YuliiaKovalova** [comment]
Blocked by this issue: https://github.com/microsoft/MSBuildLocator/issues/229
