### ISSUE TITLE
Inspect ConsoleMode before sending control codes on Windows

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#9079]
Per https://learn.microsoft.com/windows/console/console-virtual-terminal-sequences, on Windows an application should not assume VT compatibility but should call [`SetConsoleMode`](https://learn.microsoft.com/windows/console/setconsolemode) with `ENABLE_VIRTUAL_TERMINAL_PROCESSING`.

We should do this for TerminalLogger and for stderr results from #8792.

**Comment by Forgind** [comment]
Just for clarification, when you said TerminalLogger, did you mean the older ConsoleLoggers? This sounded familiar, and it turns out I enabled it for the TerminalLogger a while ago. It's moved around a bit since then, but it's still buried [here](https://github.com/dotnet/msbuild/blob/69a09e4d0ad2a26fab4100e78585c85bc2f9f5a7/src/MSBuild/XMake.cs#L2573) and [here](https://github.com/dotnet/msbuild/blob/69a09e4d0ad2a26fab4100e78585c85bc2f9f5a7/src/Build/BackEnd/Client/MSBuildClient.cs#L376).

(I was considering poking at this issue after my other PR is in 🙂)

**Comment by rainersigwald** [comment]
No, I didn't. Looks like all we need now is this for `-get*`.
