### ISSUE TITLE
Building C# project breaks hardlinks to output files since VS 17.7.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/msbuild#9183]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Building-C-project-breaks-hardlinks-to-/10440275)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.6.5]
After updating VS from 17.6.5 to 17.7.0, I noticed that building a C# project would systematically break any hardlink to the output .dlls or .exe files. 
It seems to only happen in 17.7.0 (I tried rolling back and didn't have this issue in 17.6.5) and reproductible with any C# project.

---
#### Feedback Bot on 8/15/2023, 04:56 AM: 

(private comment, text removed)
#### Zhengye Xu [MSFT] on 8/15/2023, 11:28 AM: 

(private comment, text removed)
#### Loïc Lerat on 8/15/2023, 03:58 PM: 

(private comment, text removed)
#### Feedback Bot on 8/16/2023, 00:06 PM: 

(private comment, text removed)
#### Drew Noakes [MSFT] on 8/24/2023, 03:09 AM: 

(private comment, text removed)
#### Drew Noakes [MSFT] on 8/24/2023, 01:02 PM: 

(private comment, text removed)
#### Feedback Bot on 8/24/2023, 01:02 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rainersigwald** [comment]
This changed in 17.7 as a result of fixing https://github.com/dotnet/msbuild/issues/8273, where writing through the link caused files in NuGet caches to be corrupted.

I think the new behavior is more correct, since it fixes that and the issue @KalleOlaviNiemitalo points out. If you want a pointer to "whatever is in the output folder after the build" I think what you want is a symlink, not a hardlink.
