### ISSUE TITLE
[Bug]: <MSBuild> build target fails when csproj specifies frameworks using <TargetFrameworks>

### ISSUE THREAD

**Issue by bhaeussermann** [dotnet/msbuild#9224]
### Issue Description

I have a platform-independent dependency project that targets the `net6.0` framework.
Further, I have a main project that needs to target both `net6.0` and `net6.0-windows` and have a project reference to the dependency project.
I also have an MSBuild props file that packages all projects into one NuGet package when you `dotnet pack` the main project.

When I specify a single target framework for the main project using `<TargetFramework>` the project builds fine. However, if I just change the element to `<TargetFrameworks>` (plural), then building the project fails with the following error:

```
C:\Program Files\dotnet\sdk\7.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1005: Assets file 'C:\Projects\AdHoc\MSBuildTarget\Dependency\obj\project.assets.json' doesn't have a target for 'net6.0-windows'. Ensure that restore has run and that you have included 'net6.0-windows' in the TargetFrameworks for your project.
```

Here's the main project _csproj_ file with the project reference using a `PackAsRuntime` attribute so as to trigger the relevant target in the props file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0-windows</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dependency\Dependency.csproj" PackAsRuntime="true" />
  </ItemGroup>

</Project>
```

Here is the props file that is used that declares `PackAsRuntime`:

```
<Project>
	<Target
        Name="IncludePackAsRuntimeProjectReferences"
        AfterTargets="AfterCompile"
        Condition="'@(ProjectReference)' != '' and @(ProjectReference->AnyHaveMetadataValue('PackAsRuntime', 'true'))">
		
		<MSBuild Projects="@(ProjectReference->WithMetadataValue('PackAsRuntime', 'true'))" Targets="GetPackAsRuntimeFiles" />
	</Target>

	<Target Name="GetPackAsRuntimeFiles" DependsOnTargets="$(GenerateNuspecDependsOn)">
	</Target>
</Project>
```

When I build the main project, I get the following error:

```
C:\Program Files\dotnet\sdk\7.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1005: Assets file 'C:\Projects\AdHoc\MSBuildTarget\Dependency\obj\project.assets.json' doesn't have a target for 'net6.0-windows'. Ensure that restore has run and that you have included 'net6.0-windows' in the TargetFrameworks for your project.
```

[MSBuildTarget.zip](https://github.com/dotnet/msbuild/files/12647217/MSBuildTarget.zip)

### Steps to Reproduce

A sample project that demonstrates the issue is attached.
The following command manifests the issue (or build the solution via Visual Studio):

```
dotnet build Main
```

### Expected Behavior

Building the project outputs the binaries for the `net6.0-windows` framework target and does not fail.

### Actual Behavior

Building the project fails when `<TargetFrameworks>` is used in the main project instead of `<TargetFramework>`

### Versions & Configurations

Visual Studio: 17.7.4

MSBuild: MSBuild version 17.7.2+d6990bcfa for .NET Framework
17.7.2.37605

**Comment by rainersigwald** [comment]
Invokin `<MSBuild` manually on `@(ProjectReference)` items is tricky because you have to take special care to pass additional properties in the same way that the common targets do, or you'll be building a different instance of the project (with different global properties).

https://github.com/dotnet/msbuild/blob/caf06d19326f9e7dcc06d4d4f4b04f1c6ddae5f0/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2085C8-L2092

In your case, because your `<MSBuild` invocation doesn't have `RemoveProperties="TargetFramework"`, the `TargetFramework` global property from the `net6.0-windows` "inner build" of your referencing project is inherited by the project created by the `<MSBuild` task. Since that TF wasn't specified for the referenced project at restore time, you get the "haven't restored for this TF" error.

**Comment by bhaeussermann** [comment]
Thanks @rainersigwald!
Adding `RemoveProperties="TargetFramework"` got me a step further, though I'm not sure why it's not needed when using `<TargetFramework>` in the csproj instead of `<TargetFrameworks>`.

Either way, I've now run into a problem when building the NuGet package that also relates to `<TargetFrameworks>`. I created a [separate issue](https://github.com/dotnet/msbuild/issues/9230) for it.

**Comment by rainersigwald** [comment]
> I'm not sure why it's not needed when using `<TargetFramework>` in the csproj instead of `<TargetFrameworks>`.

This is because multitargeted projects work like this from the MSBuild engine perspective:

* The project starts building with no TF specified as a global property
* That build, the "outer build", imports build logic that, instead of building stuff, _invokes the inner builds for each `TargetFramework` in `$(TargetFrameworks)`_.
* It does that by building _itself_ (the same `.csproj`) but with an additional specified global property: `TargetFramework={}`
* Those projects (the "inner builds") then do their own build stuff . . . but when they call to other builds they will (by default, unless `RemoveProperties` is specified) **pass along** the global properties they're built with.

So you get

```mermaid
graph TD
A[Referencing<br/>Single-targeted] --> B[Referenced<br/>TF=*defined in project*]

Multi[Referencing<br/>Multitargeted] -->|TF=tf1| Multi_tf1[Referencing inner<br />TF=tf1]
Multi -->|TF=tf2| Multi_tf2[Referencing inner<br />TF=tf2]
Multi_tf1 -->|your MSBuild call| B_tf1[Referenced<br/>TF=tf1]
Multi_tf2 -->|your MSBuild call| B_tf2[Referenced<br/>TF=tf2]
```
