### ISSUE TITLE
Change xliff-tasks dependency in Version.Details.xml when consuming Arcade 9

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/msbuild#9366]
We merged the xliff-tasks repo into arcade which requires us to update the Version.Details.xml entry in all repositories. I see that msbuild doesn't yet use Arcade Latest (9.0) but when it does, this change should be mimicked in the dependency update PR:

https://github.com/dotnet/razor/pull/9493/commits/fcd1831fc9e41281965fa640f088b096c38454e6

**Comment by rainersigwald** [comment]
We won't be on Arcade 9 for ~9 months and hopefully we'll remember this then :-P

Thanks!

**Comment by ViktorHofer** [comment]
Why doesn't msbuild use Arcade 9 in main when other toolset repositories like testfx, vstest, roslyn and templating do?

**Comment by rainersigwald** [comment]
At a theoretical level, that seems very broken to me since we'll be shipping in .NET 8 for several more releases.

Practically, we're pretty entangled with the .NET SDK we use to build ourselves because of how we do our bootstrap construction, so moving ahead to .NET 9 alphas makes it harder to test our repo. We could probably fix this but I've spent time on it before and it's fairly complicated.
