### ISSUE TITLE
[Broken Build]: OK in Visual Studio but NU1604 in command line

### ISSUE THREAD

**Issue by sungam3r** [dotnet/msbuild#9368]
### Issue Description

Hi. I have 2 packages, say Derived and Base. Base package has .props file with property `<MyVersion>1.2.3</MyVersion>` among other properties. This props file is properly packed I see it thanks to NugetPackageExplorer. Next, Derived package consumes Base package: `<PackageReference Include="Base" Version="1.0.0" PrivateAssets="all" />`. Also Derived package has another PackageReference like that: `<PackageReference Include="OtherPackage" Version="$(MyVersion)" />`. Does such usage possible? Now I have restore error NU1604. I called `dotnet restore -v diag` and saw that the value of `OtherPackage.Version` is actually an empty string. So the general question here is - how can I (if I can) import  variable from one package that is intended to be used as the value of `PackageReference.Version` in my other package?

### Steps to Reproduce

Since I feel that described issue is likely a general usage question I hope it does not require sample. I'm fine to provide sample otherwise.

### Expected Behavior

Restore is successful.

### Actual Behavior

Restore failed.

**Comment by sungam3r** [comment]
The weird thing is that I can successfully build `Derived` package from Visual Studio. All dependencies in the created package have versions exactly as I want (from `Base` package) but `dotnet restore`/`dotnet build` from command line (local or CI server) fails with a lot of `NU1604: Project dependency does not contain an inclusive lower bound ...` errors.

**Comment by baronfel** [comment]
You cannot do this today. Properties from one package cannot be used as part of the version specification of another package because none of the props and targets from a package exist locally until after a restore has been run - which is after the last of PackageReferences has already been decided on.

**Comment by sungam3r** [comment]
😞 But VS does it somehow. Maybe there is some workaround like manual intervention in MSBuild targets chaining?

**Comment by baronfel** [comment]
VS completely separates the build and restore phases, and is a completely different mechanism than a restore-time build. Essentially what you're asking for would need 3 (at minimum) and potentially unbounded repeated `Restore` calls, because each subsequent `Restore` could provide properties (in the respective packages' props and targets) that would then influence the _next_ round of `Restores`. This is a key reason why `Restore` as a single-run independent workflow was established in the CLI tooling today.

**Comment by sungam3r** [comment]
Thanks for explanation.
