### ISSUE TITLE
[Bug]: VersionSuffix is adding a hash in dotnet 8

### ISSUE THREAD

**Issue by Jase7** [dotnet/msbuild#9434]
### Issue Description

In any project built with dotnet 8 when adding a version suffix it's adding a hash that should not be there.
For instance, when doing: `dotnet build -c Release -p:VersionPrefix=1.3.5 -p:VersionSuffix=dev.105`

I've made a simple console app to test it (it's an standard new console app project)
[ConsoleApp1-dotnet8.zip](https://github.com/dotnet/msbuild/files/13391000/ConsoleApp1-dotnet8.zip)

### Steps to Reproduce

1. Create a new project (console app, web api or whatever)  or download the attached one

2. Build it with: `dotnet build -c Release -p:VersionPrefix=1.3.5 -p:VersionSuffix=dev.105` (change the numbers to your desire) 

### Expected Behavior

The product version of the resulting `.dll` should be 1.3.5-dev.105

### Actual Behavior

In the details of the `.dll` it's adding a hash after the version suffix that I don't know where it comes from.

![image](https://github.com/dotnet/msbuild/assets/8275823/04a40c93-962f-4400-9f17-7bc541476870)

### Versions & Configurations

In dotnet 7 was running flawless

**Comment by baronfel** [comment]
This is a documented breaking change in the SDK for .NET 8 that yo can read more about [here](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/source-link).

**Comment by Jase7** [comment]
thanks a lot! @baronfel

**Comment by radj307** [comment]
I encountered this when my github actions build script started doing this unexpectedly since it uses the newest .NET version by default. I'm writing this to hopefully get this issue to show up in more search results as this took a few tries to find.

From the page that baronfel linked about the source link feature:  
> If your build process or code doesn't expect Source Revision information in `InformationalVersion`, you can disable the new behavior by setting the `IncludeSourceRevisionInInformationalVersion` property to false in your project file.

If you have multiple project files and don't want to add `IncludeSourceRevisionInInformationalVersion` to each one, you can use a `Directory.Build.props` file in your solution dir with the following content:  
```props
<?xml version="1.0" encoding="utf-8"?>
<Project>
	<PropertyGroup>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>
</Project>
```

I don't understand why this was made the default behavior, regardless of the claimed benefits of "rich editor tooling" *(not even sure what that means)*. It seems to me like the wrong move to make people have to *add* a property to *disable* a feature that will mangle product versions in previously-working project files. But hey, if it's well documented at least people upgrading to .NET 8 on their own machines will know what to expect. 
I still wouldn't be surprised if there are a lot of stackoverflow questions being posted about this in the near future.

**Comment by ScarletKuro** [comment]
I created an doc issue in case if anyone wasn't to discuss https://github.com/dotnet/docs/issues/38404

> I still wouldn't be surprised if there are a lot of stackoverflow questions being posted about this in the near future, as I certainly didn't expect this to be default behaviour.

There area already 4 issues on the ms repositories, and I saw minimum one in stackoverflow.

But yea, I think this issue should have more attention, because it's not something I expected when upgrading the TFM to .net8.
