### ISSUE TITLE
[Bug]: Microsoft.EntityFrameworkCore.Sqlite how to prevent all the runtime binaries from being emitted? 

### ISSUE THREAD

**Issue by catmanjan** [dotnet/msbuild#9451]
### Issue Description

I've logged this here https://github.com/dotnet/efcore/issues/32382

We have a project which only runs on windows x64 and uses Microsoft.EntityFrameworkCore.Sqlite

I notice in the bin folder there are sqlite dependencies for just about every computer on earth... How can we prevent these from being emitted?

and was asked to follow up with msbuild team

We use efcore in our project however we only target win-x64 environments, can msbuild do something to allow efcore to only emit the architecture files needed for supported architectures.

### Steps to Reproduce

Add efcore to a project which only targets win-x64 and build it, check the bin folder and you will see that all the architectures are included.

### Expected Behavior

Only the architectures we are targetting should make it to the bin folder.

### Actual Behavior

All architectures are in the bin folder.

**Comment by f-alizada** [comment]
Hello @catmanjan.
Thank you for raising the issue. 
After investigation and reproducing the issue, it was identified that this is sdk behaviour by design
It seems that the issue was already opened for SDK team https://github.com/dotnet/sdk/issues/37147, thank you for that. 
Meanwhile if there is a need to build only for some specific architecture it is possible to use RuntimeIdentifier as was suggested in comment: https://github.com/NuGet/Home/issues/13039#issuecomment-1825303224

cc @JanKrivanek, @baronfel maybe something that could be considered as part of https://github.com/dotnet/msbuild/issues/9380
