### ISSUE TITLE
Duplicate Items are logged when KeepDuplicates="false"

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#9585]
```xml
<Project>

  <ItemGroup>
    <Item Include="A;B;B" KeepDuplicates="false" />
  </ItemGroup>

  <Target Name="Message">
    <ItemGroup>
      <File Include="@(Item)" KeepDuplicates="false" />
    </ItemGroup>
    <Message Text="@(File->'%(Identity)', ' ')" />
    <Message Text="@(Item->'%(Identity)', ' ')" />
  </Target>

</Project>
```

We log the File item as A B B however only A and B are actually added. I think we must be logging before the duplicates are removed?

![image](https://github.com/dotnet/msbuild/assets/679326/e868446a-4c41-4294-bf07-8554e56a2625)

**Comment by KirillOsenkov** [comment]
Also, on line 4, should KeepDuplicates="false" deduplicate A;B;B to just A;B?

**Comment by KirillOsenkov** [comment]
If it all worked properly, this would be a nifty replacement to the RemoveDuplicates task.

**Comment by SimaTian** [comment]
@KirillOsenkov ad
> Also, on line 4, should KeepDuplicates="false" deduplicate A;B;B to just A;B?

according to [this](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2022#BKMK_KeepDuplicates), no:

> If an item is generated within a target, the item element can contain the KeepDuplicates attribute. 

The Item you reference is not within a target. I just got burned by this exact issue while experimenting with the flag. I'm not sure why this distinction exists however removing it could be a breaking change.

**Comment by SimaTian** [comment]
Already tracked under [this](https://github.com/dotnet/msbuild/issues/1124) which is a larger refactoring effort.

I've got the logging fix ready and I will be submitting a PR shortly. However that is only a half fix. (Fixing small cosmetic issue within the scope of this ticket, leaving rest unattended)

Possible follow up:
  - creating a built time opt in check (to not emit additional warning and still have a better visibility) to point out that KeepDuplicates within an Item outside a target is treated as a normal metadatum and doesn't do anything about duplicates. (Too late for making it reserved keyword since that could break people due to an error/warning emission)
  - going through with the unification of the behavior. 
     - create a common point for remove duplicates functionality
     - retarget the inside of the target evaluation to it
     - figure out a proper place somewhere between ProjectParser.cs and Evaluator.cs. [Probably around here](https://github.com/dotnet/msbuild/blob/main/src/Build/Evaluation/Evaluator.cs#L699), though it will need support in the parser as well.
  - making the documentation more explicit about this behavior. Currently it is "clear" english wise, but kind of fuzzy as in "not screaming large enough about a possible caveat"

**Comment by KirillOsenkov** [comment]
Interesting that the MSBuild language service extension correctly reports that it's not supported for evaluation:

![Image](https://github.com/user-attachments/assets/5d13438b-2daa-4fbd-a067-90f8abfd57af)

**Comment by KirillOsenkov** [comment]
Confirmed that the logging piece is fixed, it logs the deduplicated items:

![Image](https://github.com/user-attachments/assets/02841ba1-ba23-4f23-891b-78327b75ccbe)
