### ISSUE TITLE
[Performance]: RAR is 1.8x slower in MSBuild.exe compared to dotnet build

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#9592]
There's a significant difference between Framework and Core MSBuild in the time taken up by the `ResolveAssemblyReference` when building OrchardCore.

Details:
- Upstream OrchardCore at commit 2804ec773.
- MSBuild 17.9 candidate (commit 5fcddc790 but unlikely to make a difference)
- Command lines (after doing a restore and build):
  - `dotnet build --no-restore /bl`
  - `msbuild /m /bl`

![image](https://github.com/dotnet/msbuild/assets/12206368/45149a44-ee0f-46fd-98d1-b7ad346d4e5b)

## Expected output

- Understand what makes MSBuild.exe slower. Are some of the optimizations introduced in 8.0 not kicking in?
- Fix (or suggest a fix; depending on complexity) the perf gap.

**Comment by YuliiaKovalova** [comment]
After conducting an investigation, a couple of weak spots were identified:

- A slow function call within mscorlib.SystemIO - Microsoft.IO.Redist was utilized to address this performance gap.
- TaskItem.CopyMetadataTo is slower in execution due to the underlying system.collections.immutable.
- Invoking SystemState.FileExists in an executable is more costly due to underlying PInvoke operations.

The next step involves analyzing the performance results with Ladi to determine if these identified gaps can be rectified.

**Comment by YuliiaKovalova** [comment]
The investigation is done and conclusions are described above.
The potential work items is created for async logging + optimization for File traversal was applied.
