### ISSUE TITLE
Analyzers prototyping - Loading and acquisition

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9633]
### Context

#9627

Built-in analyzers will be part of MSBuild (but separate assembly probably?), custom will be possible to plug-in post-installation.
Analyzer management module will need to be able to discover and load analuzers - to provide them to the infractructure (that can then register and configure them based on the default and user configuration)

### Things to be investigated and decided

* Just investigation and proposal (no implementation yet - V1 will be just manual) - The story of acquiring custom analyzers - using msbuild restore phase would be convenient for this but might prevent execution of some analysis (as analyzers might not be available during restore). Another option is similar story to template engine - dedicated commands for searching/listing/installing analyzers while searching and installing use nuget client and server API.
* Roslyn current implementation and what can we reuse

**Comment by rainersigwald** [comment]
## Brain dump

I think we agree that the _ideal_ situation for .NET projects is to get MSBuild analzyers via NuGet package reference, just like acquiring additional build logic or Roslyn source analyzers/generators.

For C++ NuGet isn't pervasive so we might need to coordinate with them for their ideal desires.

NuGet can have assets in the `project.assets.json` file that get rendered into items at build time, and can also set up build logic that will be imported by the project evaluation that happens at build time.

Any registration of analyzers within the project will run into similar problems: some of the analysis rules we'd like to enable would be best run _during evaluation_--things like rules on condition expressions, rules about defining or not defining certain properties in certain locations, and so on. If we haven't discovered and enabled all of the relevant analyzers already _before evaluation starts_, we either can't have rules like that or have to unconditionally buffer all the relevant analysis state or events until we do, then replay them through the analyzers.

Roslyn analyzers don't have this problem because they can't be discovered _within the compiler_--they're discovered by the MSBuild layer and then a flat list is passed to the compiler at its initialization/command line start time.

That's an option for MSBuild analyzers too but has two big problems:

* Cumbersome to enable (you have to change a script or something that invokes MSBuild or the `Directory.Build.rsp` and with some kind of absolute path)
* Incompatible with package-based *distribution* of analyzers (they wouldn't exist on a fresh clone, so even if you were willing to construct the path `dotnet build -buildanalyzer:/home/user/.nuget/whatever/net8.0/WhateverAnalyzer.dll` wouldn't work during `Restore`.

Analyzers could be entirely offline--working on a binlog replay, so you can assemble the analyzers during build somehow and then analyze afterward. This could even be transparent to the user (if build discovers analyzers automatically replay the binlog after the build completes but before we exit).

There could also be special handling for analyzers in NuGet restore--some kind of special file that we look at before starting to evaluate a project that has analyzer registrations in it. However, this would ideally be in `obj`, just like `project.assets.json`, and the location of `obj` is configurable via property--so we might have to (partially?) evaluate the project to find the analyzers then evaluate the project!

There's a possibility of making some kind of analyzer configuration note in memory during restore and using it during build, but that wouldn't work when the restore and build steps are in separate processes/invocations.

**Comment by rainersigwald** [comment]
As a flow I don't mind that too much but how would it work concretely? What would `dotnet build install-analyzer` do and how would subsequent `dotnet build` invocations pick it up?

**Comment by YuliiaKovalova** [comment]
> As a flow I don't mind that too much but how would it work concretely? What would `dotnet build install-analyzer` do and how would subsequent `dotnet build` invocations pick it up?

`dotnet build install-analyzer` will allow to restore custom analyzers (nuget package?) - basically it downloads and unpacks them.

**Comment by rainersigwald** [comment]
> Can we afford to have something of our own?

I would rate this as a big con of an approach that requires it, but not necessarily rule it out entirely.

**Comment by rainersigwald** [comment]
> basically it downloads and unpacks them.

That part makes sense, but how does a subsequent `build` invocation know where they are and that they should be hooked up?

**Comment by YuliiaKovalova** [comment]
> > basically it downloads and unpacks them.
> 
> That part makes sense, but how does a subsequent `build` invocation know where they are and that they should be hooked up?

Options provided by @JanKrivanek:
1. Hardcoded well known folder (e.g. '.analyzers' next to projectfile or in any folder up the folder structure - similar to how .git, .editorconfig etc. work), everything in that folder is loaded;
2. Custom configuration file (e.g. analyzers.json) - again, similar location logic as .editorconfig;
3. Mentioned in msbuild project files (same as roslyn)

**Comment by YuliiaKovalova** [comment]
Existing constraints:
1. VS doesn't rely on the command line, and we may need to provide an alternative way of communication if analysis is required for the build.
2. Modifying the Restore target can be problematic since it is a feature request for the NuGet team.
3. The existing mechanism adds information about packages to the .props file in the obj folder too late; some evaluation data may not be available anymore.
4. Creating a separate CLI is conforming to the current standard setup by Roslyn analyzers.
5. Hooking using .rsp file is possible, but analyzer packages may not be restored yet. .rsp capabilities are restricted now and don't allow to do package restore.
6. Adding sources to the repo (the plan to have a folder with all rules) isn't a good practice and can cause pushback from customers (perhaps we can put the sources in the .vs folder).
7. Currently, handling Roslyn rules is managed by the SDK itself, which goes through package.json files and searches for dedicated packages using pattern matching - we don't plan to rely on this experience.

Subproblems to the mentioned above:
1 - "checked into the repo" == how do we express what analyzers are wanted (probably the package reference, but would we need something else as well?).
2 - "at or after restore" == this is the part where we'll need to somewhere (obj? .vs? elsewhere?) store information that analyzers are wanted and where to find them.
3 - "for each analyzed build invocation" == this is the part where we need to be able to 'wake up analyzer' and if we detect that it's not woken up early enough, then give some meaningful error with good workaround.
