### ISSUE TITLE
Can TerminalLogger calm down on multi-line error/warning messages?

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#9666]
Given a multi-line error

```xml
<Project>

<PropertyGroup>
  <ErrorText><![CDATA[A
Multi
Line
Error]]>
  </ErrorText>
</PropertyGroup>

<Target Name="Go">
  <Error Text="$(ErrorText)" />
</Target>

</Project>
```

The output is . . . a lot

![screenshot with formatting](https://github.com/dotnet/msbuild/assets/3347530/445fb86c-6e5a-463b-815c-1a0c03dbf89b)

<details>
<summary>text version</summary>

```sh-session
❯ msbuild .\long_error.proj
MSBuild version 17.10.0-preview-24067-01+f1448f158 for .NET Framework
  long_error failed with errors (0.0s)
    S:\play\long_error\long_error.proj(12,3): error : A [S:\play\long_error\long_error.proj]
S:\play\long_error\long_error.proj(12,3): error : Multi [S:\play\long_error\long_error.proj]
S:\play\long_error\long_error.proj(12,3): error : Line [S:\play\long_error\long_error.proj]
S:\play\long_error\long_error.proj(12,3): error : Error [S:\play\long_error\long_error.proj]

Build failed with errors in 0.0s
```

</details>

Could it be more like

```sh-session
❯ msbuild .\long_error.proj
MSBuild version 17.10.0-preview-24067-01+f1448f158 for .NET Framework
  long_error failed with errors (0.0s)
    S:\play\long_error\long_error.proj(12,3): error : 
      A 
      Multi
      Line
      Error

Build failed with errors in 0.0s
```

?

**Comment by rainersigwald** [comment]
This came up when looking at https://github.com/dotnet/runtime/issues/97211.

**Comment by MichalPavlik** [comment]
The code producing metadata on each line is here: https://github.com/dotnet/msbuild/blob/36ab632fa286fec91434241db9ac813431727c79/src/Shared/EventArgsFormatting.cs#L353

Method `EventArgsFormatting.FormatEventMessage` is invoked by more loggers so we have to keep backward compatibility. We could do it by modifying the existing one or create new one tailored for terminal (and reuse as much as possible from the existing one).

@rainersigwald, what about the project name suffix? I think it's redundant, because the project name is also in prefix.

**Comment by rainersigwald** [comment]
> @rainersigwald, what about the project name suffix? I think it's redundant, because the project name is also in prefix.

I agree, feels redundant to put it on every line when it was already in the "section header".
