### ISSUE TITLE
Static graph construction does not use a shared evaluation context

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#9678]
With a tiny API consumer project (reference `Microsoft.Build.MSBuildLocator` and `Microsoft.Build`:

```c#
using Microsoft.Build.Graph;
using Microsoft.Build.Locator;

namespace GraphBuilderApp
{
    internal class Program
    {
        static void Main(string[] args)
        {
            MSBuildLocator.RegisterDefaults();
            DoMSBuildStuff();
        }

        private static void DoMSBuildStuff()
        {
            ProjectGraph graph = new ProjectGraph(@"C:\src\msbuild\MSBuild.sln");

            System.Console.WriteLine($"Projects in the solution: {graph.ProjectNodes.Count}");
        }
    }
}
```

Run under tracing and look at events like `Microsoft-Build/SdkResolverServiceFindResolversManifests/Stop` and `Microsoft-Build/SdkResolverResolveSdk/Stop`. In my test run (on the MSBuild repo), I see a lot of wasted work:

| Event | Count | Total time |
|--------|--------:|--------:|
| `FindResolversManifests`| 84| 597ms |
| `SdkResolverResolveSdk`| 314 | 17,328ms |

Debugging through, each project evaluated by the graph is in its own `EvaluationContext`, so they share nothing--including the list of resolvers.

**Comment by AndyGerlicher** [comment]
Just to add some info here. Here is my before/after fixing this on the client side.

With `EvaluationContext.SharingPolicy.Shared`:
```
Static graph loaded in 5.975 seconds: 811 nodes, 4299 edges
```
With default (`EvaluationContext.SharingPolicy.Isolated`):
```
Static graph loaded in 10.701 seconds: 811 nodes, 4299 edges
```

This is pretty significant! Definitely worth updating the default.

**Comment by leonardochaia** [comment]
hi @rainersigwald , sorry to hijack this old issue. 

I know the driver for this issue was to use a shared `EvaluationContext` in order to prevent repeating work.
However, this feature would also allow me to create a `ProjectGraph` which uses a custom `MSBuildFileSystemBase`. (related to #7956) (we use a custom based file system which allows us to build a `ProjectGraph` from a git commit)

I was expecting to be able to do this:
```csharp
var evaluationContext = EvaluationContext.Create(EvaluationContext.SharingPolicy.Shared, fileSystem);
ProjectGraph.ProjectInstanceFactoryFunc fn = (projectPath, globalProperties, projectCollection) =>
{
    return new ProjectInstance(
        projectPath,
        globalProperties,
        "current",
        subToolsetVersion: null,
        projectCollection,
        evaluationContext); // << Fails due to internal constructor
};

var entrypoints = allProjects.Select(p => new ProjectGraphEntryPoint(p));
var output = new ProjectGraph(entrypoints, ProjectCollection.GlobalProjectCollection, fn);
```

But unfortunately I cannot instantiate a `ProjectInstance` supplying an `EvaluationContext` since the constructor is `internal`. Is this intentional?

If so, should I raise a new issue to support this feature?

Thank you :+1: 
Leo.
