### ISSUE TITLE
Assemblies loaded during UsingTask not reported

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#9839]
For this project file:

```xml
<Project>

  <UsingTask
    TaskName="Copy"
    AssemblyFile="C:\users\kirill\.nuget\packages\microsoft.build.copyonwrite\1.0.282\build\netstandard2.0\Microsoft.Build.CopyOnWrite.dll" />

  <Target Name="Build">
    <Copy SourceFiles="Q:\temp\1.txt" DestinationFiles="Q:\temp\2.txt" SkipUnchangedFiles="true">
      <Output TaskParameter="DestinationFiles" ItemName="FileWritesShareable"/>
      <Output TaskParameter="CopiedFiles" ItemName="ReferencesCopiedInThisBuild"/>
      <Output TaskParameter="WroteAtLeastOneFile" PropertyName="WroteAtLeastOneFile"/>
    </Copy>
  </Target>

</Project>
```

there's no indication that the Microsoft.Build.CopyOnWrite.dll has loaded anywhere in the binlog

**Comment by rainersigwald** [comment]
I see it in the "task loaded from" message:

![image](https://github.com/dotnet/msbuild/assets/3347530/6aa8d7d6-329c-4d34-887b-677c074e231f)

Were you expecting it somewhere else?

**Comment by KirillOsenkov** [comment]
yes I thought it will show up when I search for Loaded assembly (but for whatever reason AssemblyLoaded handler doesn't see the assembly?)

**Comment by rainersigwald** [comment]
Ah, that makes sense, now that we have that we should maybe retrofit it to the original assembly load. I bet it's not showing up there because we don't hook up the load monitoring until after reflection-loading the entrypoint assembly. _Might_ be a quick fix to move that around . . .

**Comment by KirillOsenkov** [comment]
the problem is that CopyOnWrite is not in the box and I'd expect it to be loaded pretty late, roughly when we evaluate UsingTask. Would be nice to dig in and understand why that is.

**Comment by JanKrivanek** [comment]
The reason for the type not being reported by the `AssemblyLoadsTracker` is the name of the assembly - as it mimicks the 1st pty assembly names.

In order to minimize 'spaming' of thise feature - we filter out tracking for components (tasks, loggers, sdks), that appears to be built-in:

https://github.com/dotnet/msbuild/blob/0764e8979bd4e98c85d0ef9ef8220a8b52bfe4b3/src/Build/BackEnd/Components/RequestBuilder/AssemblyLoadsTracker.cs#L89-L99


The heuristic could surely be improved, but it is a niche scenario. Ideally `Microsoft.Build` should not be used for non-1st-pty tasks.

@KirillOsenkov - does that sound acceptable? Alternatively - if you can come up with solid and simple alterantive heuristic distinguishing 1st pty components assemblies - we can discuss improving the current algo.

**Comment by KirillOsenkov** [comment]
ah, I see, thanks for digging in!

I just wanted to make sure we're not accidentally missing events.

this filtering is fine. Given that the task reports the assembly I think we can close.
