### ISSUE TITLE
[Bug]: Doc titles are not indexed in bing-searches correctly

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/msbuild#9909]
### Issue Description

Titles for articles like [The `ProjectReference` Protocol](https://github.com/dotnet/msbuild/blob/main/documentation/ProjectReference-Protocol.md) don't seem to show up correctly in web-searches. 

They look like "The" instead of the full title. 

![image](https://github.com/dotnet/msbuild/assets/20246435/536e2565-454b-442d-ba18-cfe8d9c995cc)

Looks like the problem may be coming from the use of code-quoting. 

### Steps to Reproduce

https://www.bing.com/search?q=projectreference+protocol+github

This seems to be unique to bing. Google is a bit better. 

### Expected Behavior

Web searches show the full title like "The ProjectReference Protocol"

### Actual Behavior

"The" is all that shows up.

**Comment by rainersigwald** [comment]
Looks like a problem with the Bing scraper since I see the same in DDG:

![image](https://github.com/dotnet/msbuild/assets/3347530/532c1075-6657-47d1-ad70-20fba7e5e7fa)

but Google displays something else:

![image](https://github.com/dotnet/msbuild/assets/3347530/51cce301-9ad2-4852-8f1b-3399891d3da8)

I filed internal Bing feedback (and tried to cc you @vatsan-madhavan).

I would rather not change the repo for this display issue in search so I'm closing this; if it persists or spreads though we can accommodate it.

**Comment by rainersigwald** [comment]
Bing reported as fixed, though I still see the behavior (maybe waiting on a rollout?)

**Comment by vatsan-madhavan** [comment]
Seems to be working for me - must be a rollout audience thing. 

![image](https://github.com/dotnet/msbuild/assets/20246435/972bfa9d-53c0-4e50-b704-f593f4f726d8)
