### ISSUE TITLE
[Bug]: Valid BCP 47 tags in the resource file name not recognized

### ISSUE THREAD

**Issue by PopSlime** [dotnet/msbuild#9954]
### Issue Description

I was trying to add support of an uncommon language to my app with resource files, before I realized its language tag was not being recognized by MSBuild, and it was not generating the expected satellite assembly for that language.

### Steps to Reproduce

1. Create a project with three resource files: `Resources.resx`, `Resources.zh.resx`, and `Resources.yue.resx`.
2. Build the project.

### Expected Behavior

The satellite assemblies for both `zh` and `yue` are generated.

### Actual Behavior

The satellite assembly for `zh` is generated, but the one for `yue` is not.

### Analysis

I suspect that the following code is causing this issue.

https://github.com/dotnet/msbuild/blob/7ca3c98fad986066bbf2802c863236b4a0f4e34a/src/Tasks/CultureInfoCache.cs#L70

A valid language code is not necessarily predefined.

**Comment by rainersigwald** [comment]
@KalleOlaviNiemitalo is correct: the long-standing behavior of MSBuild is to attempt to detect localized resources based on the cultures available to _the OS that is running the build_. If you want to use specific culture that may not be defined in all of your build environments, specify it explicitly with `Culture` metadata to bypass the detection. And by extension since you can't completely control what your OS vendor does with cultures: it's a good idea to do that for all language-specific resources.

**Comment by PopSlime** [comment]
As far as I can see, MSBuild is not handling this `Culture` metadata correctly as well at the moment. It still tries to infer the culture from the file name even if the `Culture`, `WithCulture`, and `DependentUpon` metadata is explicitly set, and even ends up failing the build if the `Culture` metadata mismatches with the culture inferred from the file name.

**Comment by PopSlime** [comment]
By the way, for now I have modified this logic, built it, and replaced the `Microsoft.Build.Tasks.Core.dll` locally and it worked perfectly on my project.

![3d13c4e468c2efc95917e1ce056a90ca](https://github.com/dotnet/msbuild/assets/61138090/2dec2756-11da-40ee-82cb-231a86305941)

**Comment by f-alizada** [comment]
Hi everyone :) 

1.  Culture metadata is not respected during the identifying the culture info and is overriden even if presented. Code: https://github.com/dotnet/msbuild/blob/053feb0db1845c96e2e9a60e676039d1503b916f/src/Tasks/AssignCulture.cs#L134-L154
2. Supporting Test: https://github.com/dotnet/msbuild/blob/053feb0db1845c96e2e9a60e676039d1503b916f/src/Tasks.UnitTests/AssignCulture_Tests.cs#L44-L58
3. The Documentation says otherwise : https://learn.microsoft.com/en-us/visualstudio/msbuild/assignculture-task?view=vs-2022

We have discussed with @rainersigwald (thank you! ) some approaches: Order of the items more preferred to less 

1. Introduce a new 'Property': if set to 'true', the approach described in Documentation will run 
2. Introduce new metadata for EmbeddedResource 
3. Change the approach according to the documentation, but put the change behind the change wave

@baronfel Could you please share your opinion on the approaches ? :) 
Thank you in advance!

**Comment by rainersigwald** [comment]
@KalleOlaviNiemitalo that's a good idea! Pros: small change. Cons: doesn't fully resolve the "is `cs` Czech or C#?" problem we've run into so would still require setting `WithCulture="false"` on some files.

**Comment by baronfel** [comment]
There's some precedent for allow-lists of known resources - the `SatelliteResourceLanguages` property exists to 'filter' the resources for packages/dependencies of a project to a certain well-known set. Could we start looking at this property as an input to the culture-lookup? Potentially with @KalleOlaviNiemitalo's property as a more-specific override?

**Comment by f-alizada** [comment]
Thank you @KalleOlaviNiemitalo, @baronfel, and @rainersigwald for your input!
I was mostly thinking of addressing the inconsistency between the documentation and the actual implementation (to align the behavior). However, adding a new list of supported languages brings an additional parameter to the Task (list of cultures) that needs to be respected during the build. I believe this is out of the scope of this issue (please correct me if I'm wrong) :)

Any approach introduced here will be opt-in, also the I think a good direction for the culture specific files is to have the Culture set explicitly (For reference: https://github.com/dotnet/msbuild/issues/9882). 

Please feel free to correct me if I stated/understood something incorrectly :)
